"""ADIA Lab Structural Break Real-Time — self-contained submission.

AUTO-GENERATED by scripts/make_submission3.py from src/sb/features{2,3,4}.py —
do not edit by hand; edit the sources and regenerate so train/serve stay in
parity.

Strategy (round 3): O(1) streaming tracker with PER-SERIES EMPIRICAL-NULL
CALIBRATION + a deterministic LightGBM seed/feature-set ensemble.
  * Every window statistic is normalised by the null loc/scale measured on the
    series' own break-free historical segment at dyadic scales (8..512).
    TS-AUC is a cross-sectional ranking, so per-series calibration is what
    makes scores comparable across heterogeneous DGPs — this was the round-3
    breakthrough (held-out VAL 0.581 -> 0.60+).
  * Features: multiscale calibrated window stats + scan/running-max, AR(1)-
    prewhitened CUSUM bank, derived-stream (|z| / dz / median-crossing)
    calibrated windows, and null-calibrated higher-moment (skew/kurt) windows.
  * Ensemble members blended by mean-logit (learned stacking was tried and
    rejected — it overfits the ranking metric).

Deterministic (no RNG in the feature path; LightGBM deterministic=True).
"""
from __future__ import annotations

import os
from typing import Iterable, List, Optional, Tuple

import joblib
import bisect
import math
from collections import deque

import numpy as np

EWMA_ALPHAS = (0.05, 0.20)
CUSUM_KS = (0.25, 0.5, 1.0)   # mean-CUSUM allowances (sensitivity ladder)
CUSUM_VAR_K = 0.5
DIST_WINDOWS = (25, 50, 100, 200, 400)
DIFF_WINDOW = 50
N_EDGES = 19

NULL_GRID = (8, 16, 32, 64, 128, 256, 512)   # dyadic null-calibration scales
_LOG2_GRID = [math.log2(g) for g in NULL_GRID]
PW_CUSUM_KS = (0.25, 0.5)
PW_EWMA_ALPHA = 0.10

_BASE_NAMES = [
    "t", "log_t", "log_n_hist", "t_over_nhist",
    "cum_mean_z", "cum_mean_dev", "cum_logvar_ratio",
    "cum_skew", "cum_kurt", "cum_skew_diff", "cum_kurt_diff",
    "ewma_z_fast", "ewma_z_slow",
    "tail2_excess", "tail3_excess",
    "online_acf1", "acf1_diff",
    "ks_stat", "ecdf_l1", "below_hist_med_excess",
    "cusum_var_absmax", "cusum_var_absmax_n", "ph_mean", "ph_mean_n",
    "dvar_ratio_cum", "dvar_ratio_win", "dabs_ratio_cum",
    "chi2_cum", "online_acf2", "acf2_diff",
]
_CUSUM_NAMES = []
for _k in CUSUM_KS:
    tag = str(_k).replace(".", "")
    _CUSUM_NAMES += [f"cusum_absmax_k{tag}", f"cusum_absmax_k{tag}_n"]
_WIN_NAMES = []
for _W in DIST_WINDOWS:
    _WIN_NAMES += [f"w{_W}_mean_z", f"w{_W}_logvar", f"w{_W}_skew",
                   f"w{_W}_kurt", f"w{_W}_ks", f"w{_W}_acf1_diff", f"w{_W}_chi2",
                   f"w{_W}_l1",
                   f"w{_W}_nmz", f"w{_W}_nlv", f"w{_W}_nacf", f"w{_W}_nks",
                   f"w{_W}_nl1"]
_SCAN_NAMES = ["scan_nmz", "scan_nlv", "scan_nacf", "scan_nks", "scan_nl1",
               "rm_scan_nmz", "rm_scan_nlv", "rm_scan_nacf", "rm_scan_nks",
               "rm_scan_nl1"]
_PW_NAMES = ["pw_cusum_absmax_k025", "pw_cusum_absmax_k025_n",
             "pw_cusum_absmax_k05", "pw_cusum_absmax_k05_n",
             "pw_cusum_var_absmax", "pw_cusum_var_absmax_n",
             "pw_ewma_z", "pw_cum_mean_z", "pw_cum_logvar", "pw_acf1"]
_CONST_NAMES = ["acf1_h", "kurt_h", "null_smz64", "null_slv64", "null_sacf64",
                "null_mem_slope"]

_FN2 = (_BASE_NAMES + _CUSUM_NAMES + _WIN_NAMES + _SCAN_NAMES
                 + _PW_NAMES + _CONST_NAMES)
_NF2 = len(_FN2)


class WindowDist:
    """Fixed-size trailing window with O(1) moment / eCDF / acf maintenance."""

    __slots__ = ("W", "q", "s1", "s2", "s3", "s4", "bins", "bin_counts",
                 "prod_sum", "n_pairs", "n_edges")

    def __init__(self, W: int, n_edges: int) -> None:
        self.W = W
        self.n_edges = n_edges
        self.reset()

    def reset(self) -> None:
        self.q = deque()
        self.s1 = self.s2 = self.s3 = self.s4 = 0.0
        self.bins = deque()
        self.bin_counts = [0] * (self.n_edges + 1)
        self.prod_sum = 0.0
        self.n_pairs = 0

    def push(self, x: float, b: int) -> None:
        q = self.q
        if q:
            self.prod_sum += q[-1] * x
            self.n_pairs += 1
        q.append(x)
        self.s1 += x
        xx = x * x
        self.s2 += xx
        self.s3 += xx * x
        self.s4 += xx * xx
        self.bins.append(b)
        self.bin_counts[b] += 1
        if len(q) > self.W:
            ox = q.popleft()
            self.prod_sum -= ox * q[0]
            self.n_pairs -= 1
            oxx = ox * ox
            self.s1 -= ox
            self.s2 -= oxx
            self.s3 -= oxx * ox
            self.s4 -= oxx * oxx
            self.bin_counts[self.bins.popleft()] -= 1

    def stats(self, mu_h, sd_h, var_h, hist_cdf, acf1_h):
        """Raw two-sample stats vs historical: returns
        (mean_z, logvar, skew, kurt, ks, acf1_diff, chi2, l1, cw)."""
        cw = len(self.q)
        mean = self.s1 / cw
        var = max(self.s2 / cw - mean * mean, 0.0)
        mean_z = (mean - mu_h) / max(sd_h / math.sqrt(cw), 1e-9)
        logvar = math.log(max(var, 1e-12) / max(var_h, 1e-12))
        if cw > 2 and var > 1e-12:
            sd = math.sqrt(var)
            m3 = self.s3 / cw - 3 * mean * (self.s2 / cw) + 2 * mean ** 3
            m4 = (self.s4 / cw - 4 * mean * (self.s3 / cw)
                  + 6 * mean ** 2 * (self.s2 / cw) - 3 * mean ** 4)
            skew = m3 / (sd ** 3)
            kurt = m4 / (var * var) - 3.0
        else:
            skew = kurt = 0.0
        run = 0
        ks = 0.0
        l1 = 0.0
        inv = 1.0 / cw
        bc = self.bin_counts
        nb = self.n_edges + 1
        exp = cw / nb            # historical bins are ~equiprobable by construction
        inv_exp = 1.0 / exp
        chi2 = 0.0
        for j in range(self.n_edges):
            run += bc[j]
            d = abs(run * inv - hist_cdf[j])
            l1 += d
            if d > ks:
                ks = d
            dd = bc[j] - exp
            chi2 += dd * dd
        # last bin (above top edge)
        dd = bc[self.n_edges] - exp
        chi2 = (chi2 + dd * dd) * inv_exp
        l1 /= self.n_edges
        if self.n_pairs > 1 and var > 1e-12:
            acf1 = (self.prod_sum / self.n_pairs - mean * mean) / var
            acf1 = max(min(acf1, 1.0), -1.0)
        else:
            acf1 = 0.0
        return mean_z, logvar, skew, kurt, ks, acf1 - acf1_h, chi2, l1, cw


def _slide_sum(c: np.ndarray, g: int) -> np.ndarray:
    """Sliding-window sums of width g from a cumsum array c (1-D)."""
    return c[g:] - c[:-g]


class _Det2:
    """Maintains streaming state for a single series; reset per series."""

    __slots__ = (
        "mu_h", "sd_h", "var_h", "skew_h", "kurt_h", "acf1_h", "acf2_h", "median_h",
        "dvar_h", "dabs_h", "edges", "hist_cdf", "n_hist",
        "n", "s1", "s2", "s3", "s4", "ewma", "neff",
        "cusum_pos", "cusum_neg", "cusum_absmax",
        "cusum_var_pos", "cusum_var_neg", "cusum_var_absmax",
        "cumz", "mincum", "maxcum", "tail2", "tail3",
        "ac_cross", "ac_n", "ac_lastx", "ac_lastx2", "ac2_cross", "ac2_n",
        "ac_sx", "ac_sx2",
        "bin_counts", "below_med",
        "d_n", "d_s1", "d_s2", "d_abs", "dwin_q", "dwin_s1", "dwin_s2",
        "windows",
        # --- v2 ---
        "null_loc", "null_scale", "phi", "pw_denom", "z_prev",
        "pw_cusum_pos", "pw_cusum_neg", "pw_cusum_absmax",
        "pw_cusum_var_pos", "pw_cusum_var_neg", "pw_cusum_var_absmax",
        "pw_ewma", "pw_neff", "pw_s1", "pw_s2",
        "pw_ac_cross", "pw_ac_n", "pw_e_prev",
        "rm_scan", "const_feats",
    )

    def __init__(self) -> None:
        self.windows = [WindowDist(W, N_EDGES) for W in DIST_WINDOWS]
        self.reset_baseline()

    # ------------------------------------------------------------------ #
    # null-table machinery
    # ------------------------------------------------------------------ #
    def _default_nulls(self) -> None:
        # loc/scale per stat per grid scale; iid-Gaussian-flavoured defaults
        nl, ns = {}, {}
        for st in ("mz", "lv", "acf", "ks", "l1"):
            nl[st] = [0.0] * len(NULL_GRID)
            ns[st] = [1.0] * len(NULL_GRID)
        for i, g in enumerate(NULL_GRID):
            ns["mz"][i] = 1.0
            ns["lv"][i] = math.sqrt(2.0 / g)
            nl["lv"][i] = -1.0 / g
            ns["acf"][i] = 1.0 / math.sqrt(g)
            nl["ks"][i] = 0.86 / math.sqrt(g)
            ns["ks"][i] = 0.35 / math.sqrt(g)
            nl["l1"][i] = 0.4 / math.sqrt(g)
            ns["l1"][i] = 0.2 / math.sqrt(g)
        self.null_loc, self.null_scale = nl, ns

    def _interp(self, table: list, cw: int) -> float:
        """Log2-linear interpolation of a per-scale null parameter at fill cw."""
        lx = math.log2(cw) if cw > 1 else 1.0
        if lx <= _LOG2_GRID[0]:
            return table[0]
        if lx >= _LOG2_GRID[-1]:
            return table[-1]
        i = int(lx - _LOG2_GRID[0])  # grid is consecutive powers of two
        f = lx - _LOG2_GRID[i]
        return table[i] * (1.0 - f) + table[i + 1] * f

    def _calibrate_nulls(self, z: np.ndarray, bins_h: np.ndarray) -> None:
        """Measure per-series null loc/scale of window stats on the
        (break-free) historical segment at dyadic scales."""
        n = z.size
        self._default_nulls()
        if n < 64:
            return
        c1 = np.concatenate(([0.0], np.cumsum(z)))
        c2 = np.concatenate(([0.0], np.cumsum(z * z)))
        cross = z[:-1] * z[1:]
        cc = np.concatenate(([0.0], np.cumsum(cross)))
        nb = N_EDGES + 1
        onehot = bins_h[:, None] == np.arange(nb)[None, :]
        B = np.concatenate((np.zeros((1, nb)), np.cumsum(onehot, axis=0)))
        qarr = np.asarray(self.hist_cdf)

        for i, g in enumerate(NULL_GRID):
            if g > n // 2:
                # not enough data: copy previous scale (already iid default)
                for st in ("mz", "lv", "acf", "ks", "l1"):
                    self.null_loc[st][i] = self.null_loc[st][i - 1] if i else self.null_loc[st][i]
                    self.null_scale[st][i] = self.null_scale[st][i - 1] if i else self.null_scale[st][i]
                continue
            means = _slide_sum(c1, g) / g
            mz = means * math.sqrt(g)            # z-units: mu=0, sd=1
            v = np.maximum(_slide_sum(c2, g) / g - means * means, 1e-12)
            lv = np.log(v)
            # acf1 within window: pairs i..i+g-2
            cs = (cc[g - 1:] - cc[: n - g + 2 - 1])[: means.size] / (g - 1)
            acf = np.clip((cs - means * means) / v, -1.0, 1.0)
            acfd = acf - self.acf1_h
            stride = max(1, g // 8)
            sl = slice(0, None, stride)
            self.null_loc["mz"][i] = float(np.mean(mz[sl]))
            self.null_scale["mz"][i] = max(float(np.std(mz[sl])), 0.05)
            self.null_loc["lv"][i] = float(np.mean(lv[sl]))
            self.null_scale["lv"][i] = max(float(np.std(lv[sl])), 0.01)
            self.null_loc["acf"][i] = float(np.mean(acfd[sl]))
            self.null_scale["acf"][i] = max(float(np.std(acfd[sl])), 0.01)
            # KS / L1 on a strided subsample (heavier)
            stride_k = max(1, g // 4)
            pos = np.arange(0, n - g + 1, stride_k)
            counts = B[pos + g] - B[pos]                       # (P, nb)
            F = np.cumsum(counts, axis=1)[:, :N_EDGES] / g     # (P, 19)
            D = np.abs(F - qarr[None, :])
            ks = D.max(axis=1)
            l1 = D.mean(axis=1)
            ks_med = float(np.median(ks))
            l1_med = float(np.median(l1))
            self.null_loc["ks"][i] = ks_med
            self.null_scale["ks"][i] = max(float(np.quantile(ks, 0.9)) - ks_med, 0.005)
            self.null_loc["l1"][i] = l1_med
            self.null_scale["l1"][i] = max(float(np.quantile(l1, 0.9)) - l1_med, 0.003)

    # ------------------------------------------------------------------ #
    def reset_baseline(self) -> None:
        self.mu_h = 0.0
        self.sd_h = 1.0
        self.var_h = 1.0
        self.skew_h = self.kurt_h = self.acf1_h = self.acf2_h = self.median_h = 0.0
        self.dvar_h = 1.0
        self.dabs_h = 1.0
        self.n_hist = 0
        self.edges = list(np.linspace(-1, 1, N_EDGES))
        self.hist_cdf = [k / (N_EDGES + 1) for k in range(1, N_EDGES + 1)]
        self._default_nulls()
        self.phi = 0.0
        self.pw_denom = 1.0
        self.z_prev = 0.0
        self.const_feats = (0.0, 0.0, 1.0, 0.1, 0.1, 0.0)
        self._reset_online()

    def _reset_online(self) -> None:
        self.n = 0
        self.s1 = self.s2 = self.s3 = self.s4 = 0.0
        self.ewma = [0.0 for _ in EWMA_ALPHAS]
        self.neff = [0.0 for _ in EWMA_ALPHAS]
        self.cusum_pos = [0.0 for _ in CUSUM_KS]
        self.cusum_neg = [0.0 for _ in CUSUM_KS]
        self.cusum_absmax = [0.0 for _ in CUSUM_KS]
        self.cusum_var_pos = self.cusum_var_neg = self.cusum_var_absmax = 0.0
        self.cumz = self.mincum = self.maxcum = 0.0
        self.tail2 = self.tail3 = 0
        self.ac_cross = 0.0
        self.ac_n = 0
        self.ac_lastx = None
        self.ac_lastx2 = None
        self.ac2_cross = 0.0
        self.ac2_n = 0
        self.ac_sx = self.ac_sx2 = 0.0
        self.bin_counts = [0] * (N_EDGES + 1)
        self.below_med = 0
        self.d_n = 0
        self.d_s1 = self.d_s2 = self.d_abs = 0.0
        self.dwin_q = deque()
        self.dwin_s1 = self.dwin_s2 = 0.0
        for w in self.windows:
            w.reset()
        # --- v2 online state ---
        self.pw_cusum_pos = [0.0 for _ in PW_CUSUM_KS]
        self.pw_cusum_neg = [0.0 for _ in PW_CUSUM_KS]
        self.pw_cusum_absmax = [0.0 for _ in PW_CUSUM_KS]
        self.pw_cusum_var_pos = self.pw_cusum_var_neg = 0.0
        self.pw_cusum_var_absmax = 0.0
        self.pw_ewma = 0.0
        self.pw_neff = 0.0
        self.pw_s1 = self.pw_s2 = 0.0
        self.pw_ac_cross = 0.0
        self.pw_ac_n = 0
        self.pw_e_prev = None
        self.rm_scan = [0.0] * 5

    def calibrate(self, x_hist) -> None:
        x = np.asarray(x_hist, dtype=np.float64)
        n = x.size
        if n == 0:
            self.reset_baseline()
            return
        self.n_hist = int(n)
        mu = float(x.mean())
        sd = float(x.std(ddof=1)) if n > 1 else 1.0
        sd = max(sd, 1e-9)
        z = (x - mu) / sd
        self.mu_h = mu
        self.sd_h = sd
        self.var_h = sd * sd
        self.skew_h = float((z ** 3).mean()) if n > 2 else 0.0
        self.kurt_h = float((z ** 4).mean() - 3.0) if n > 3 else 0.0
        self.median_h = float(np.median(x))
        if n > 2:
            xc = x - mu
            denom = float(np.dot(xc, xc))
            self.acf1_h = float(np.dot(xc[:-1], xc[1:]) / denom) if denom > 0 else 0.0
            self.acf2_h = float(np.dot(xc[:-2], xc[2:]) / denom) if (denom > 0 and n > 3) else 0.0
        else:
            self.acf1_h = 0.0
            self.acf2_h = 0.0
        if n > 2:
            dx = np.diff(x)
            self.dvar_h = max(float(dx.var()), 1e-9)
            self.dabs_h = max(float(np.abs(dx).mean()), 1e-9)
        else:
            self.dvar_h = 1.0
            self.dabs_h = 1.0
        qs = np.linspace(1.0 / (N_EDGES + 1), N_EDGES / (N_EDGES + 1), N_EDGES)
        edges = np.quantile(x, qs)
        edges = np.maximum.accumulate(edges + np.arange(N_EDGES) * 1e-12)
        self.edges = edges.tolist()
        self.hist_cdf = qs.tolist()

        # --- v2: per-series empirical nulls + prewhitening setup ---
        bins_h = np.searchsorted(edges, x, side="right")
        self._calibrate_nulls(z, bins_h)
        self.phi = max(min(self.acf1_h, 0.95), -0.95)
        self.pw_denom = math.sqrt(max(1.0 - self.phi * self.phi, 1e-4))
        self.z_prev = float(z[-1])
        smz64 = self.null_scale["mz"][3]
        slv64 = self.null_scale["lv"][3]
        sacf64 = self.null_scale["acf"][3]
        mem_slope = math.log(max(self.null_scale["mz"][5], 1e-6)
                             / max(self.null_scale["mz"][1], 1e-6))
        self.const_feats = (self.acf1_h, self.kurt_h, smz64, slv64, sacf64,
                            mem_slope)
        self._reset_online()

    def update(self, x: float) -> np.ndarray:
        mu_h, sd_h = self.mu_h, self.sd_h
        z = (x - mu_h) / sd_h
        self.n += 1
        self.s1 += x
        xx = x * x
        self.s2 += xx
        self.s3 += xx * x
        self.s4 += xx * xx

        for i, a in enumerate(EWMA_ALPHAS):
            self.ewma[i] = (1.0 - a) * self.ewma[i] + a * x if self.neff[i] > 0 else x
            self.neff[i] = (1.0 - a) * self.neff[i] + 1.0

        # multi-k mean CUSUM
        for i, kk in enumerate(CUSUM_KS):
            cp = self.cusum_pos[i] + z - kk
            if cp < 0.0:
                cp = 0.0
            cn = self.cusum_neg[i] - z - kk
            if cn < 0.0:
                cn = 0.0
            self.cusum_pos[i] = cp
            self.cusum_neg[i] = cn
            m = cp if cp > cn else cn
            if m > self.cusum_absmax[i]:
                self.cusum_absmax[i] = m

        # variance CUSUM on (z^2 - 1)
        zz1 = z * z - 1.0
        self.cusum_var_pos = max(0.0, self.cusum_var_pos + zz1 - CUSUM_VAR_K)
        self.cusum_var_neg = max(0.0, self.cusum_var_neg - zz1 - CUSUM_VAR_K)
        mv = self.cusum_var_pos if self.cusum_var_pos > self.cusum_var_neg else self.cusum_var_neg
        if mv > self.cusum_var_absmax:
            self.cusum_var_absmax = mv

        # Page-Hinkley two-sided drift
        self.cumz += z
        if self.cumz < self.mincum:
            self.mincum = self.cumz
        if self.cumz > self.maxcum:
            self.maxcum = self.cumz

        az = -z if z < 0 else z
        if az > 2.0:
            self.tail2 += 1
        if az > 3.0:
            self.tail3 += 1

        # autocorr (lag-1 & lag-2) accumulators + first-difference trackers
        prev1 = self.ac_lastx
        prev2 = self.ac_lastx2
        if prev1 is not None:
            self.ac_cross += prev1 * x
            self.ac_n += 1
            dx = x - prev1
            self.d_n += 1
            self.d_s1 += dx
            self.d_s2 += dx * dx
            self.d_abs += -dx if dx < 0 else dx
            dq = self.dwin_q
            dq.append(dx)
            self.dwin_s1 += dx
            self.dwin_s2 += dx * dx
            if len(dq) > DIFF_WINDOW:
                od = dq.popleft()
                self.dwin_s1 -= od
                self.dwin_s2 -= od * od
        if prev2 is not None:
            self.ac2_cross += prev2 * x
            self.ac2_n += 1
        self.ac_lastx2 = prev1
        self.ac_lastx = x
        self.ac_sx += x
        self.ac_sx2 += xx

        b = bisect.bisect_right(self.edges, x)
        self.bin_counts[b] += 1
        if x < self.median_h:
            self.below_med += 1

        for w in self.windows:
            w.push(x, b)

        # --- v2: prewhitened residual trackers ---
        e = (z - self.phi * self.z_prev) / self.pw_denom
        self.z_prev = z
        for i, kk in enumerate(PW_CUSUM_KS):
            cp = self.pw_cusum_pos[i] + e - kk
            if cp < 0.0:
                cp = 0.0
            cn = self.pw_cusum_neg[i] - e - kk
            if cn < 0.0:
                cn = 0.0
            self.pw_cusum_pos[i] = cp
            self.pw_cusum_neg[i] = cn
            m = cp if cp > cn else cn
            if m > self.pw_cusum_absmax[i]:
                self.pw_cusum_absmax[i] = m
        ee1 = e * e - 1.0
        self.pw_cusum_var_pos = max(0.0, self.pw_cusum_var_pos + ee1 - CUSUM_VAR_K)
        self.pw_cusum_var_neg = max(0.0, self.pw_cusum_var_neg - ee1 - CUSUM_VAR_K)
        mv = (self.pw_cusum_var_pos if self.pw_cusum_var_pos > self.pw_cusum_var_neg
              else self.pw_cusum_var_neg)
        if mv > self.pw_cusum_var_absmax:
            self.pw_cusum_var_absmax = mv
        self.pw_ewma = ((1.0 - PW_EWMA_ALPHA) * self.pw_ewma + PW_EWMA_ALPHA * e
                        if self.pw_neff > 0 else e)
        self.pw_neff = (1.0 - PW_EWMA_ALPHA) * self.pw_neff + 1.0
        ep = self.pw_e_prev
        if ep is not None:
            self.pw_ac_cross += ep * e
            self.pw_ac_n += 1
        self.pw_e_prev = e
        self.pw_s1 += e
        self.pw_s2 += e * e

        return self._features()

    def _features(self) -> np.ndarray:
        n = self.n
        mu_h, sd_h, var_h = self.mu_h, self.sd_h, self.var_h
        f = np.empty(_NF2, dtype=np.float64)
        mean_o = self.s1 / n
        var_o = max(self.s2 / n - mean_o * mean_o, 0.0)
        cum_mean_dev = (mean_o - mu_h) / sd_h
        cum_mean_z = cum_mean_dev * math.sqrt(n)
        cum_logvar = math.log(max(var_o, 1e-12) / max(var_h, 1e-12))
        if n > 2 and var_o > 1e-12:
            sd_o = math.sqrt(var_o)
            m3 = self.s3 / n - 3 * mean_o * (self.s2 / n) + 2 * mean_o ** 3
            m4 = (self.s4 / n - 4 * mean_o * (self.s3 / n)
                  + 6 * mean_o ** 2 * (self.s2 / n) - 3 * mean_o ** 4)
            cum_skew = m3 / (sd_o ** 3)
            cum_kurt = m4 / (var_o * var_o) - 3.0
        else:
            cum_skew = cum_kurt = 0.0

        ewma_z = []
        for i in range(len(EWMA_ALPHAS)):
            se = sd_h / math.sqrt(max(self.neff[i], 1.0))
            ewma_z.append((self.ewma[i] - mu_h) / max(se, 1e-9))

        tail2_excess = self.tail2 / n - 0.0455
        tail3_excess = self.tail3 / n - 0.0027

        if self.ac_n > 1:
            mac = self.ac_sx / n
            var_ac = self.ac_sx2 / n - mac * mac
            online_acf1 = (self.ac_cross / self.ac_n - mac * mac) / max(var_ac, 1e-12)
            online_acf1 = max(min(online_acf1, 1.0), -1.0)
            if self.ac2_n > 1:
                online_acf2 = (self.ac2_cross / self.ac2_n - mac * mac) / max(var_ac, 1e-12)
                online_acf2 = max(min(online_acf2, 1.0), -1.0)
            else:
                online_acf2 = 0.0
        else:
            online_acf1 = 0.0
            online_acf2 = 0.0

        run = 0
        ks_stat = 0.0
        ecdf_l1 = 0.0
        chi2_cum = 0.0
        inv_n = 1.0 / n
        exp_n = n / (N_EDGES + 1)
        bc = self.bin_counts
        hcdf = self.hist_cdf
        for j in range(N_EDGES):
            run += bc[j]
            d = abs(run * inv_n - hcdf[j])
            ecdf_l1 += d
            if d > ks_stat:
                ks_stat = d
            dd = bc[j] - exp_n
            chi2_cum += dd * dd
        dd = bc[N_EDGES] - exp_n
        chi2_cum = (chi2_cum + dd * dd) / exp_n
        below_excess = self.below_med / n - 0.5

        ph_mean = max(self.cumz - self.mincum, self.maxcum - self.cumz)
        inv_sqrt_n = 1.0 / math.sqrt(n)

        # first-difference variance / abs ratios (dependence breaks)
        if self.d_n > 1:
            dvar_cum = max(self.d_s2 / self.d_n - (self.d_s1 / self.d_n) ** 2, 0.0)
            dvar_ratio_cum = math.log(max(dvar_cum, 1e-12) / self.dvar_h)
            dabs_ratio_cum = (self.d_abs / self.d_n) / self.dabs_h
        else:
            dvar_ratio_cum = 0.0
            dabs_ratio_cum = 1.0
        cwd = len(self.dwin_q)
        if cwd > 1:
            dwin_var = max(self.dwin_s2 / cwd - (self.dwin_s1 / cwd) ** 2, 0.0)
            dvar_ratio_win = math.log(max(dwin_var, 1e-12) / self.dvar_h)
        else:
            dvar_ratio_win = 0.0

        f[0] = n - 1
        f[1] = math.log(n)
        f[2] = math.log(self.n_hist) if self.n_hist > 0 else 0.0
        f[3] = (n - 1) / self.n_hist if self.n_hist > 0 else 0.0
        f[4] = cum_mean_z
        f[5] = cum_mean_dev
        f[6] = cum_logvar
        f[7] = cum_skew
        f[8] = cum_kurt
        f[9] = cum_skew - self.skew_h
        f[10] = cum_kurt - self.kurt_h
        f[11] = ewma_z[0]
        f[12] = ewma_z[1]
        f[13] = tail2_excess
        f[14] = tail3_excess
        f[15] = online_acf1
        f[16] = online_acf1 - self.acf1_h
        f[17] = ks_stat
        f[18] = ecdf_l1
        f[19] = below_excess
        f[20] = self.cusum_var_absmax
        f[21] = self.cusum_var_absmax * inv_sqrt_n
        f[22] = ph_mean
        f[23] = ph_mean * inv_sqrt_n
        f[24] = dvar_ratio_cum
        f[25] = dvar_ratio_win
        f[26] = dabs_ratio_cum
        f[27] = chi2_cum
        f[28] = online_acf2
        f[29] = online_acf2 - self.acf2_h
        k = 30
        for i in range(len(CUSUM_KS)):
            f[k] = self.cusum_absmax[i]
            f[k + 1] = self.cusum_absmax[i] * inv_sqrt_n
            k += 2

        # ---- windows: raw + null-calibrated stats, and scan maxima ----
        nloc, nscale = self.null_loc, self.null_scale
        scan = [0.0, 0.0, 0.0, 0.0, 0.0]
        for w in self.windows:
            mz, lv, sk, ku, ks, ad, chi2, l1, cw = w.stats(
                mu_h, sd_h, var_h, hcdf, self.acf1_h)
            if cw >= 5:
                nmz = mz / self._interp(nscale["mz"], cw)
                nlv = (lv - self._interp(nloc["lv"], cw)) / self._interp(nscale["lv"], cw)
                nacf = (ad - self._interp(nloc["acf"], cw)) / self._interp(nscale["acf"], cw)
                nks = (ks - self._interp(nloc["ks"], cw)) / self._interp(nscale["ks"], cw)
                nl1 = (l1 - self._interp(nloc["l1"], cw)) / self._interp(nscale["l1"], cw)
            else:
                nmz = nlv = nacf = nks = nl1 = 0.0
            f[k] = mz; f[k + 1] = lv; f[k + 2] = sk
            f[k + 3] = ku; f[k + 4] = ks; f[k + 5] = ad; f[k + 6] = chi2
            f[k + 7] = l1
            f[k + 8] = nmz; f[k + 9] = nlv; f[k + 10] = nacf
            f[k + 11] = nks; f[k + 12] = nl1
            k += 13
            a = -nmz if nmz < 0 else nmz
            if a > scan[0]:
                scan[0] = a
            a = -nlv if nlv < 0 else nlv
            if a > scan[1]:
                scan[1] = a
            a = -nacf if nacf < 0 else nacf
            if a > scan[2]:
                scan[2] = a
            if nks > scan[3]:
                scan[3] = nks
            if nl1 > scan[4]:
                scan[4] = nl1

        rm = self.rm_scan
        for i in range(5):
            if scan[i] > rm[i]:
                rm[i] = scan[i]
        f[k] = scan[0]; f[k + 1] = scan[1]; f[k + 2] = scan[2]
        f[k + 3] = scan[3]; f[k + 4] = scan[4]
        f[k + 5] = rm[0]; f[k + 6] = rm[1]; f[k + 7] = rm[2]
        f[k + 8] = rm[3]; f[k + 9] = rm[4]
        k += 10

        # ---- prewhitened trackers ----
        f[k] = self.pw_cusum_absmax[0]
        f[k + 1] = self.pw_cusum_absmax[0] * inv_sqrt_n
        f[k + 2] = self.pw_cusum_absmax[1]
        f[k + 3] = self.pw_cusum_absmax[1] * inv_sqrt_n
        f[k + 4] = self.pw_cusum_var_absmax
        f[k + 5] = self.pw_cusum_var_absmax * inv_sqrt_n
        se = 1.0 / math.sqrt(max(self.pw_neff, 1.0))
        f[k + 6] = self.pw_ewma / max(se, 1e-9)
        f[k + 7] = self.pw_s1 * inv_sqrt_n
        f[k + 8] = math.log(max(self.pw_s2 / n, 1e-12))
        if self.pw_ac_n > 1:
            pme = self.pw_s1 / n
            pve = max(self.pw_s2 / n - pme * pme, 1e-12)
            pac = (self.pw_ac_cross / self.pw_ac_n - pme * pme) / pve
            f[k + 9] = max(min(pac, 1.0), -1.0)
        else:
            f[k + 9] = 0.0
        k += 10

        cf = self.const_feats
        f[k] = cf[0]; f[k + 1] = cf[1]; f[k + 2] = cf[2]
        f[k + 3] = cf[3]; f[k + 4] = cf[4]; f[k + 5] = cf[5]
        return f


DSTREAM_WINDOWS = (50, 200)

_DS_NAMES = []
for _W in DSTREAM_WINDOWS:
    _DS_NAMES += [f"a_nmz_w{_W}", f"a_nacf_w{_W}",
                  f"d_nmz_w{_W}", f"d_nacf_w{_W}",
                  f"x_nmz_w{_W}"]
_DS_SCAN = ["a_scan_mz", "a_scan_acf", "d_scan_mz", "d_scan_acf", "x_scan_mz",
            "rm_a_scan_mz", "rm_a_scan_acf", "rm_d_scan_mz", "rm_d_scan_acf",
            "rm_x_scan_mz"]
_DS_CONST = ["acf1_h_abs", "cross_rate_h"]

_FN3 = _FN2 + _DS_NAMES + _DS_SCAN + _DS_CONST
_NF3 = len(_FN3)
_N_V2 = len(_FN2)


class StreamWin:
    """Trailing window over a derived stream: O(1) mean + lag-1 acf."""

    __slots__ = ("W", "q", "s1", "s2", "prod_sum", "n_pairs")

    def __init__(self, W: int) -> None:
        self.W = W
        self.reset()

    def reset(self) -> None:
        self.q = deque()
        self.s1 = self.s2 = 0.0
        self.prod_sum = 0.0
        self.n_pairs = 0

    def push(self, v: float) -> None:
        q = self.q
        if q:
            self.prod_sum += q[-1] * v
            self.n_pairs += 1
        q.append(v)
        self.s1 += v
        self.s2 += v * v
        if len(q) > self.W:
            ov = q.popleft()
            self.prod_sum -= ov * q[0]
            self.n_pairs -= 1
            self.s1 -= ov
            self.s2 -= ov * ov

    def mean(self) -> float:
        return self.s1 / len(self.q)

    def acf1(self) -> float:
        cw = len(self.q)
        m = self.s1 / cw
        v = self.s2 / cw - m * m
        if self.n_pairs > 1 and v > 1e-12:
            a = (self.prod_sum / self.n_pairs - m * m) / v
            return max(min(a, 1.0), -1.0)
        return 0.0

    def size(self) -> int:
        return len(self.q)


def _null_mean_acf(stream: np.ndarray, grid=NULL_GRID):
    """Per-scale null loc/scale of sliding mean and sliding acf1 of a stream."""
    n = stream.size
    loc_m = [0.0] * len(grid)
    sc_m = [1.0] * len(grid)
    loc_a = [0.0] * len(grid)
    sc_a = [1.0] * len(grid)
    if n < 64:
        return loc_m, sc_m, loc_a, sc_a
    c1 = np.concatenate(([0.0], np.cumsum(stream)))
    c2 = np.concatenate(([0.0], np.cumsum(stream * stream)))
    cross = stream[:-1] * stream[1:]
    cc = np.concatenate(([0.0], np.cumsum(cross)))
    for i, g in enumerate(grid):
        if g > n // 2:
            loc_m[i] = loc_m[i - 1] if i else 0.0
            sc_m[i] = sc_m[i - 1] if i else 1.0
            loc_a[i] = loc_a[i - 1] if i else 0.0
            sc_a[i] = sc_a[i - 1] if i else 1.0
            continue
        means = _slide_sum(c1, g) / g
        v = np.maximum(_slide_sum(c2, g) / g - means * means, 1e-12)
        cs = (cc[g - 1:] - cc[: n - g + 1]) / (g - 1)
        acf = np.clip((cs - means * means) / v, -1.0, 1.0)
        stride = max(1, g // 8)
        sl = slice(0, None, stride)
        loc_m[i] = float(np.mean(means[sl]))
        sc_m[i] = max(float(np.std(means[sl])), 1e-4)
        loc_a[i] = float(np.mean(acf[sl]))
        sc_a[i] = max(float(np.std(acf[sl])), 1e-3)
    return loc_m, sc_m, loc_a, sc_a


class _Det3(_Det2):
    """v2 detector + derived-stream (|z|, dz, crossing) calibrated windows."""

    __slots__ = (
        "ds_null", "median_z", "a_wins", "d_wins", "x_wins",
        "ds_rm", "ds_const", "prev_z_ds", "prev_side",
    )

    def __init__(self) -> None:
        self.ds_null = None
        self.median_z = 0.0
        self.a_wins = [StreamWin(W) for W in DSTREAM_WINDOWS]
        self.d_wins = [StreamWin(W) for W in DSTREAM_WINDOWS]
        self.x_wins = [StreamWin(W) for W in DSTREAM_WINDOWS]
        self.ds_rm = [0.0] * 5
        self.ds_const = (0.0, 0.5)
        self.prev_z_ds = 0.0
        self.prev_side = 0
        super().__init__()

    # -------------------------------------------------------------- #
    def _reset_online(self) -> None:
        super()._reset_online()
        for w in self.a_wins:
            w.reset()
        for w in self.d_wins:
            w.reset()
        for w in self.x_wins:
            w.reset()
        self.ds_rm = [0.0] * 5

    def calibrate(self, x_hist) -> None:
        super().calibrate(x_hist)
        x = np.asarray(x_hist, dtype=np.float64)
        n = x.size
        if n == 0:
            self.ds_null = None
            self.ds_const = (0.0, 0.5)
            self.prev_z_ds = 0.0
            self.prev_side = 0
            return
        z = (x - self.mu_h) / self.sd_h
        self.median_z = (self.median_h - self.mu_h) / self.sd_h
        a = np.abs(z)
        d = np.diff(z, prepend=z[0])
        side = (z > self.median_z).astype(np.float64)
        xing = np.abs(np.diff(side, prepend=side[0]))
        self.ds_null = dict(
            a=_null_mean_acf(a),
            d=_null_mean_acf(d),
            x=_null_mean_acf(xing),
        )
        # vol persistence + crossing rate as constants
        am = a - a.mean()
        den = float(np.dot(am, am))
        acf_abs = float(np.dot(am[:-1], am[1:]) / den) if den > 0 else 0.0
        self.ds_const = (acf_abs, float(xing.mean()))
        self.prev_z_ds = float(z[-1])
        self.prev_side = 1 if z[-1] > self.median_z else 0
        self._reset_online()

    # -------------------------------------------------------------- #
    def _ds_interp(self, table: list, cw: int) -> float:
        lx = math.log2(cw) if cw > 1 else 1.0
        if lx <= _LOG2_GRID[0]:
            return table[0]
        if lx >= _LOG2_GRID[-1]:
            return table[-1]
        i = int(lx - _LOG2_GRID[0])
        f = lx - _LOG2_GRID[i]
        return table[i] * (1.0 - f) + table[i + 1] * f

    def update(self, x: float) -> np.ndarray:
        f2 = super().update(x)
        z = (x - self.mu_h) / self.sd_h
        a = -z if z < 0 else z
        dz = z - self.prev_z_ds
        self.prev_z_ds = z
        side = 1 if z > self.median_z else 0
        xing = 1.0 if side != self.prev_side else 0.0
        self.prev_side = side
        for w in self.a_wins:
            w.push(a)
        for w in self.d_wins:
            w.push(dz)
        for w in self.x_wins:
            w.push(xing)

        f = np.empty(_NF3, dtype=np.float64)
        f[:_N_V2] = f2
        k = _N_V2
        scan = [0.0] * 5
        if self.ds_null is None:
            f[k:] = 0.0
            return f
        nla, nsa = self.ds_null["a"][0], self.ds_null["a"][1]
        nlaa, nsaa = self.ds_null["a"][2], self.ds_null["a"][3]
        nld, nsd = self.ds_null["d"][0], self.ds_null["d"][1]
        nlda, nsda = self.ds_null["d"][2], self.ds_null["d"][3]
        nlx, nsx = self.ds_null["x"][0], self.ds_null["x"][1]
        for i in range(len(DSTREAM_WINDOWS)):
            aw, dw, xw = self.a_wins[i], self.d_wins[i], self.x_wins[i]
            cw = aw.size()
            if cw >= 5:
                a_nmz = (aw.mean() - self._ds_interp(nla, cw)) / self._ds_interp(nsa, cw)
                a_nacf = (aw.acf1() - self._ds_interp(nlaa, cw)) / self._ds_interp(nsaa, cw)
                d_nmz = (dw.mean() - self._ds_interp(nld, cw)) / self._ds_interp(nsd, cw)
                d_nacf = (dw.acf1() - self._ds_interp(nlda, cw)) / self._ds_interp(nsda, cw)
                x_nmz = (xw.mean() - self._ds_interp(nlx, cw)) / self._ds_interp(nsx, cw)
            else:
                a_nmz = a_nacf = d_nmz = d_nacf = x_nmz = 0.0
            f[k] = a_nmz; f[k + 1] = a_nacf
            f[k + 2] = d_nmz; f[k + 3] = d_nacf
            f[k + 4] = x_nmz
            k += 5
            for si, v in enumerate((a_nmz, a_nacf, d_nmz, d_nacf, x_nmz)):
                av = -v if v < 0 else v
                if av > scan[si]:
                    scan[si] = av
        rm = self.ds_rm
        for i in range(5):
            if scan[i] > rm[i]:
                rm[i] = scan[i]
        for i in range(5):
            f[k + i] = scan[i]
        for i in range(5):
            f[k + 5 + i] = rm[i]
        k += 10
        f[k] = self.ds_const[0]
        f[k + 1] = self.ds_const[1]
        return f


HM_WINDOWS = (100, 200, 400, 800)

_HM_NAMES = []
for _W in HM_WINDOWS:
    _HM_NAMES += [f"hm{_W}_nskew", f"hm{_W}_nkurt"]
_HM_SCAN = ["hm_scan_skew", "hm_scan_kurt",
            "rm_hm_scan_skew", "rm_hm_scan_kurt"]
_HM_CONST = ["null_skurt128"]

FEATURE_NAMES = _FN3 + _HM_NAMES + _HM_SCAN + _HM_CONST
N_FEATURES = len(FEATURE_NAMES)
_N_V3 = len(_FN3)


class MomentWin:
    """Trailing window with O(1) skew / excess-kurt via running power sums."""

    __slots__ = ("W", "q", "s1", "s2", "s3", "s4")

    def __init__(self, W: int) -> None:
        self.W = W
        self.reset()

    def reset(self) -> None:
        self.q = deque()
        self.s1 = self.s2 = self.s3 = self.s4 = 0.0

    def push(self, x: float) -> None:
        q = self.q
        q.append(x)
        xx = x * x
        self.s1 += x
        self.s2 += xx
        self.s3 += xx * x
        self.s4 += xx * xx
        if len(q) > self.W:
            ox = q.popleft()
            oxx = ox * ox
            self.s1 -= ox
            self.s2 -= oxx
            self.s3 -= oxx * ox
            self.s4 -= oxx * oxx

    def skew_kurt(self):
        cw = len(self.q)
        if cw < 3:
            return 0.0, 0.0, cw
        mean = self.s1 / cw
        var = self.s2 / cw - mean * mean
        if var <= 1e-12:
            return 0.0, 0.0, cw
        sd = math.sqrt(var)
        m3 = self.s3 / cw - 3 * mean * (self.s2 / cw) + 2 * mean ** 3
        m4 = (self.s4 / cw - 4 * mean * (self.s3 / cw)
              + 6 * mean ** 2 * (self.s2 / cw) - 3 * mean ** 4)
        return m3 / (sd ** 3), m4 / (var * var) - 3.0, cw

    def size(self) -> int:
        return len(self.q)


def _null_skew_kurt(z: np.ndarray, grid=NULL_GRID):
    """Per-scale null loc/scale of sliding-window skew and excess kurt on the
    break-free historical segment."""
    n = z.size
    loc_s = [0.0] * len(grid)
    sc_s = [math.sqrt(6.0 / g) for g in grid]
    loc_k = [0.0] * len(grid)
    sc_k = [math.sqrt(24.0 / g) for g in grid]
    if n < 64:
        return loc_s, sc_s, loc_k, sc_k
    c1 = np.concatenate(([0.0], np.cumsum(z)))
    c2 = np.concatenate(([0.0], np.cumsum(z * z)))
    c3 = np.concatenate(([0.0], np.cumsum(z ** 3)))
    c4 = np.concatenate(([0.0], np.cumsum(z ** 4)))
    for i, g in enumerate(grid):
        if g > n // 2:
            if i:
                loc_s[i], sc_s[i] = loc_s[i - 1], sc_s[i - 1]
                loc_k[i], sc_k[i] = loc_k[i - 1], sc_k[i - 1]
            continue
        m1 = _slide_sum(c1, g) / g
        m2 = _slide_sum(c2, g) / g
        m3raw = _slide_sum(c3, g) / g
        m4raw = _slide_sum(c4, g) / g
        var = np.maximum(m2 - m1 * m1, 1e-12)
        sd = np.sqrt(var)
        mu3 = m3raw - 3 * m1 * m2 + 2 * m1 ** 3
        mu4 = m4raw - 4 * m1 * m3raw + 6 * m1 ** 2 * m2 - 3 * m1 ** 4
        skew = mu3 / (sd ** 3)
        kurt = mu4 / (var * var) - 3.0
        stride = max(1, g // 8)
        sl = slice(0, None, stride)
        loc_s[i] = float(np.mean(skew[sl]))
        sc_s[i] = max(float(np.std(skew[sl])), 1e-3)
        loc_k[i] = float(np.mean(kurt[sl]))
        sc_k[i] = max(float(np.std(kurt[sl])), 1e-3)
    return loc_s, sc_s, loc_k, sc_k


class _Det4(_Det3):
    """v3 detector + null-calibrated higher-moment window stats."""

    __slots__ = ("hm_wins", "hm_null_sk", "hm_rm", "hm_const")

    def __init__(self) -> None:
        self.hm_wins = [MomentWin(W) for W in HM_WINDOWS]
        self.hm_null_sk = None
        self.hm_rm = [0.0, 0.0]
        self.hm_const = (1.0,)
        super().__init__()

    def _reset_online(self) -> None:
        super()._reset_online()
        for w in self.hm_wins:
            w.reset()
        self.hm_rm = [0.0, 0.0]

    def calibrate(self, x_hist) -> None:
        super().calibrate(x_hist)
        x = np.asarray(x_hist, dtype=np.float64)
        n = x.size
        if n == 0:
            self.hm_null_sk = None
            self.hm_const = (1.0,)
            return
        z = (x - self.mu_h) / self.sd_h
        self.hm_null_sk = _null_skew_kurt(z)
        self.hm_const = (self.hm_null_sk[3][4],)  # kurt null scale at scale 128
        self._reset_online()

    def _hm_interp(self, table, cw):
        lx = math.log2(cw) if cw > 1 else 1.0
        if lx <= _LOG2_GRID[0]:
            return table[0]
        if lx >= _LOG2_GRID[-1]:
            return table[-1]
        i = int(lx - _LOG2_GRID[0])
        f = lx - _LOG2_GRID[i]
        return table[i] * (1.0 - f) + table[i + 1] * f

    def update(self, x: float) -> np.ndarray:
        f3 = super().update(x)
        z = (x - self.mu_h) / self.sd_h
        for w in self.hm_wins:
            w.push(z)

        f = np.empty(N_FEATURES, dtype=np.float64)
        f[:_N_V3] = f3
        k = _N_V3
        if self.hm_null_sk is None:
            f[k:] = 0.0
            return f
        loc_s, sc_s, loc_k, sc_k = self.hm_null_sk
        scan = [0.0, 0.0]
        for w in self.hm_wins:
            sk, ku, cw = w.skew_kurt()
            if cw >= 8:
                nsk = (sk - self._hm_interp(loc_s, cw)) / self._hm_interp(sc_s, cw)
                nku = (ku - self._hm_interp(loc_k, cw)) / self._hm_interp(sc_k, cw)
            else:
                nsk = nku = 0.0
            f[k] = nsk
            f[k + 1] = nku
            k += 2
            a = -nsk if nsk < 0 else nsk
            if a > scan[0]:
                scan[0] = a
            a = -nku if nku < 0 else nku
            if a > scan[1]:
                scan[1] = a
        rm = self.hm_rm
        if scan[0] > rm[0]:
            rm[0] = scan[0]
        if scan[1] > rm[1]:
            rm[1] = scan[1]
        f[k] = scan[0]; f[k + 1] = scan[1]
        f[k + 2] = rm[0]; f[k + 3] = rm[1]
        k += 4
        f[k] = self.hm_const[0]
        return f


StreamingDetector = _Det4


# ----------------------------------------------------------------------------
# Competition interface
# ----------------------------------------------------------------------------
# Feature-name subsets per feature-set version (each ensemble member trains and
# predicts on its own subset of the shared v4 feature vector).
_DEFAULT_DROP = {
    "t", "log_n_hist", "chi2_cum", "online_acf2", "acf2_diff",
    "w25_chi2", "w50_chi2", "w100_chi2", "w200_chi2", "w400_chi2",
}
_NAME_SET = set(FEATURE_NAMES)


def _keep_for(version):
    if version == "v2":
        allowed = set(_FN2)
    elif version == "v3":
        allowed = set(_FN3)
    else:
        allowed = set(FEATURE_NAMES)
    return [i for i, n in enumerate(FEATURE_NAMES)
            if n in allowed and n not in _DEFAULT_DROP]


LGB_PARAMS = dict(
    objective="binary", metric="None", boosting_type="gbdt",
    num_leaves=31, learning_rate=0.03, feature_fraction=0.8,
    bagging_fraction=0.8, bagging_freq=1, min_data_in_leaf=1000,
    num_threads=0, seed=42, deterministic=True, force_row_wise=True,
    verbosity=-1,
)
# (seed, num_rounds, feature-version) — rounds frozen from local TS-AUC selection
ENSEMBLE = [(42, 374, 'v2'), (7, 231, 'v2'), (2026, 306, 'v2'), (42, 348, 'v4')]
RAMP = 50.0        # down-weight near-undetectable fresh-break positives
# A logistic-regression member on the v2 feature subset adds genuine model-class
# diversity (corr ~0.93 with the GBTs vs 0.97-0.99 GBT-GBT). Blend is
# final_logit = (1-W_LIN)*mean(GBT logits) + W_LIN*logistic_logit.
W_LIN = 0.2
LOGI_C = 0.5


def _build_xyw(datasets):
    det = StreamingDetector()
    X_chunks, y_chunks, w_chunks = [], [], []
    for _id, x_hist, x_online, tau in datasets:
        det.calibrate(np.asarray(x_hist, dtype=np.float64))
        T = len(x_online)
        if T == 0:
            continue
        feats = np.empty((T, N_FEATURES), dtype=np.float32)
        for i, x in enumerate(x_online):
            feats[i] = det.update(float(x))
        y = np.zeros(T, dtype=np.int8)
        w = np.ones(T, dtype=np.float64)
        if tau is not None and tau >= 0:
            tau = int(tau)
            y[tau:] = 1
            idx = np.arange(T)
            w[tau:] = np.clip((idx[tau:] - tau) / RAMP, 0.2, 1.0)
        X_chunks.append(feats)
        y_chunks.append(y)
        w_chunks.append(w)
    return (np.vstack(X_chunks), np.concatenate(y_chunks),
            np.concatenate(w_chunks))


def train(
    datasets: List[Tuple[int, List[float], List[float], Optional[int]]],
    model_directory_path: str,
):
    """Fit the deterministic LightGBM ensemble + logistic on streaming feats."""
    import lightgbm as lgb

    X, y, w = _build_xyw(datasets)

    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        keep = _keep_for(version)
        names = [FEATURE_NAMES[i] for i in keep]
        dtrain = lgb.Dataset(X[:, keep], label=y, weight=w, feature_name=names)
        params = dict(LGB_PARAMS, seed=seed)
        booster = lgb.train(params, dtrain, num_boost_round=rounds)
        booster.save_model(os.path.join(model_directory_path, f"lgbm_{mi}.txt"))
        del dtrain

    # logistic member on the v2 feature subset (deterministic; lbfgs).
    # Train on a deterministic row SUBSAMPLE (stride 5 -> ~1M rows) in float32:
    # the full-matrix float64 copy peaks >10 GB and OOMs the runner, while ~1M
    # rows are ample for a 117-d linear model and bound memory to ~0.5 GB.
    from sklearn.linear_model import LogisticRegression
    keep = np.asarray(_keep_for("v2"), dtype=np.int64)
    sub = slice(None, None, 5)
    Xl = X[sub][:, keep].astype(np.float32)
    np.nan_to_num(Xl, copy=False, nan=0.0, posinf=0.0, neginf=0.0)
    yl = y[sub]
    mean = Xl.mean(axis=0)
    scale = Xl.std(axis=0)
    scale[scale < 1e-9] = 1.0
    Xl -= mean
    Xl /= scale
    np.clip(Xl, -8.0, 8.0, out=Xl)
    lr = LogisticRegression(C=LOGI_C, max_iter=1000, solver="lbfgs")
    lr.fit(Xl, yl)
    del Xl
    np.savez(os.path.join(model_directory_path, "logistic.npz"),
             keep=keep, mean=mean.astype(np.float64),
             scale=scale.astype(np.float64),
             coef=lr.coef_[0], intercept=np.array([lr.intercept_[0]]))


def infer(
    datasets: Iterable[Tuple[List[float], Iterable[float]]],
    model_directory_path: str,
):
    """Stream per-step break probabilities in [0, 1] (GBT + logistic blend)."""
    import lightgbm as lgb

    boosters, keeps = [], []
    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        boosters.append(lgb.Booster(
            model_file=os.path.join(model_directory_path, f"lgbm_{mi}.txt")))
        keeps.append(_keep_for(version))
    rows = [np.empty((1, len(k)), dtype=np.float64) for k in keeps]
    w_gbt = (1.0 - W_LIN) / len(boosters)

    lg = np.load(os.path.join(model_directory_path, "logistic.npz"))
    l_keep = lg["keep"]
    l_mean = lg["mean"]
    l_scale = lg["scale"]
    l_coef = lg["coef"]
    l_int = float(lg["intercept"][0])

    det = StreamingDetector()

    yield  # signal readiness

    for x_historical, x_online in datasets:
        det.calibrate(np.asarray(x_historical, dtype=np.float64))
        for point in x_online:
            feats = det.update(float(point))
            acc = 0.0
            for b, keep, row in zip(boosters, keeps, rows):
                row[0] = feats[keep]
                p = float(b.predict(row)[0])
                p = min(max(p, 1e-7), 1.0 - 1e-7)
                acc += math.log(p / (1.0 - p)) * w_gbt
            # logistic logit on the v2 subset
            xv = feats[l_keep]
            xs = (xv - l_mean) / l_scale
            np.clip(xs, -8.0, 8.0, out=xs)
            lin_logit = float(np.dot(xs, l_coef)) + l_int
            acc += W_LIN * lin_logit
            score = 1.0 / (1.0 + math.exp(-acc))
            if score < 0.0:
                score = 0.0
            elif score > 1.0:
                score = 1.0
            yield score
