"""Generate submission/main.py inlining the full v2->v3->v4 feature chain plus
a deterministic mean-logit LightGBM ensemble that can mix feature-set recipes.

The cloud can't import our package, so we textually inline features2.py,
features3.py and features4.py into one module. Each module defines module-level
FEATURE_NAMES / N_FEATURES and a StreamingDetector; to avoid name collisions we
rename the v2/v3 copies to private names (_FN2/_NF2/_Det2, _FN3/_NF3/_Det3) and
let v4 own the public FEATURE_NAMES / N_FEATURES / StreamingDetector (the
superset, 162 features). Exact-parity with the library extractors is checked by
submission/local_test.py.

Each ensemble member is a recipe (seed, rounds, feature-version). Because v4's
feature vector is a superset of v3's and v2's (verified bit-identical), train()
builds the v4 features ONCE and trains every member on its own feature-name
subset; infer() builds v4 features once per step and each booster predicts on
its subset, blended by mean-logit. So a "v2" member reproduces the standalone
v2 model exactly while sharing one streaming pass.

Run:  uv run python scripts/make_submission3.py
"""
from __future__ import annotations

import os
import re

F2, F3, F4 = "src/sb/features2.py", "src/sb/features3.py", "src/sb/features4.py"
OUT = "submission/main.py"

HEADER = '''"""ADIA Lab Structural Break Real-Time — self-contained submission.

AUTO-GENERATED by scripts/make_submission3.py from src/sb/features{2,3,4}.py —
do not edit by hand; edit the sources and regenerate so train/serve stay in
parity.

Strategy (round 3): O(1) streaming tracker with PER-SERIES EMPIRICAL-NULL
CALIBRATION + a deterministic LightGBM seed/feature-set ensemble.
  * Every window statistic is normalised by the null loc/scale measured on the
    series' own break-free historical segment at dyadic scales (8..512).
    TS-AUC is a cross-sectional ranking, so per-series calibration is what
    makes scores comparable across heterogeneous DGPs — this was the round-3
    breakthrough (held-out VAL 0.581 -> 0.60+).
  * Features: multiscale calibrated window stats + scan/running-max, AR(1)-
    prewhitened CUSUM bank, derived-stream (|z| / dz / median-crossing)
    calibrated windows, and null-calibrated higher-moment (skew/kurt) windows.
  * Ensemble members blended by mean-logit (learned stacking was tried and
    rejected — it overfits the ranking metric).

Deterministic (no RNG in the feature path; LightGBM deterministic=True).
"""
from __future__ import annotations

import os
from typing import Iterable, List, Optional, Tuple

import joblib
'''


def _strip_to(src: str, marker: str) -> str:
    return src[src.index(marker):]


def _rename(body: str, mapping: dict) -> str:
    for a, b in mapping.items():
        body = re.sub(rf"\b{re.escape(a)}\b", b, body)
    return body


def _drop_import_block(body: str, module: str) -> str:
    """Remove a `from sb.<module> import (...)` multi-line block."""
    pat = re.compile(rf"from sb\.{module} import \([^)]*\)\n", re.S)
    return pat.sub("", body)


WRAPPER = '''

# ----------------------------------------------------------------------------
# Competition interface
# ----------------------------------------------------------------------------
# Feature-name subsets per feature-set version (each ensemble member trains and
# predicts on its own subset of the shared v4 feature vector).
_DEFAULT_DROP = {
    "t", "log_n_hist", "chi2_cum", "online_acf2", "acf2_diff",
    "w25_chi2", "w50_chi2", "w100_chi2", "w200_chi2", "w400_chi2",
}
_NAME_SET = set(FEATURE_NAMES)


def _keep_for(version):
    if version == "v2":
        allowed = set(_FN2)
    elif version == "v3":
        allowed = set(_FN3)
    else:
        allowed = set(FEATURE_NAMES)
    return [i for i, n in enumerate(FEATURE_NAMES)
            if n in allowed and n not in _DEFAULT_DROP]


LGB_PARAMS = dict(
    objective="binary", metric="None", boosting_type="gbdt",
    num_leaves=31, learning_rate=0.03, feature_fraction=0.8,
    bagging_fraction=0.8, bagging_freq=1, min_data_in_leaf=1000,
    num_threads=0, seed=42, deterministic=True, force_row_wise=True,
    verbosity=-1,
)
# (seed, num_rounds, feature-version) — rounds frozen from local TS-AUC selection
ENSEMBLE = __ENSEMBLE__
RAMP = 50.0        # down-weight near-undetectable fresh-break positives
# A logistic-regression member on the v2 feature subset adds genuine model-class
# diversity (corr ~0.93 with the GBTs vs 0.97-0.99 GBT-GBT). Blend is
# final_logit = (1-W_LIN)*mean(GBT logits) + W_LIN*logistic_logit.
W_LIN = 0.2
LOGI_C = 0.5


def _build_xyw(datasets):
    det = StreamingDetector()
    X_chunks, y_chunks, w_chunks = [], [], []
    for _id, x_hist, x_online, tau in datasets:
        det.calibrate(np.asarray(x_hist, dtype=np.float64))
        T = len(x_online)
        if T == 0:
            continue
        feats = np.empty((T, N_FEATURES), dtype=np.float32)
        for i, x in enumerate(x_online):
            feats[i] = det.update(float(x))
        y = np.zeros(T, dtype=np.int8)
        w = np.ones(T, dtype=np.float64)
        if tau is not None and tau >= 0:
            tau = int(tau)
            y[tau:] = 1
            idx = np.arange(T)
            w[tau:] = np.clip((idx[tau:] - tau) / RAMP, 0.2, 1.0)
        X_chunks.append(feats)
        y_chunks.append(y)
        w_chunks.append(w)
    return (np.vstack(X_chunks), np.concatenate(y_chunks),
            np.concatenate(w_chunks))


def train(
    datasets: List[Tuple[int, List[float], List[float], Optional[int]]],
    model_directory_path: str,
):
    """Fit the deterministic LightGBM ensemble + logistic on streaming feats."""
    import lightgbm as lgb

    X, y, w = _build_xyw(datasets)

    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        keep = _keep_for(version)
        names = [FEATURE_NAMES[i] for i in keep]
        dtrain = lgb.Dataset(X[:, keep], label=y, weight=w, feature_name=names)
        params = dict(LGB_PARAMS, seed=seed)
        booster = lgb.train(params, dtrain, num_boost_round=rounds)
        booster.save_model(os.path.join(model_directory_path, f"lgbm_{mi}.txt"))
        del dtrain

    # logistic member on the v2 feature subset (deterministic; lbfgs).
    # Train on a deterministic row SUBSAMPLE (stride 5 -> ~1M rows) in float32:
    # the full-matrix float64 copy peaks >10 GB and OOMs the runner, while ~1M
    # rows are ample for a 117-d linear model and bound memory to ~0.5 GB.
    from sklearn.linear_model import LogisticRegression
    keep = np.asarray(_keep_for("v2"), dtype=np.int64)
    sub = slice(None, None, 5)
    Xl = X[sub][:, keep].astype(np.float32)
    np.nan_to_num(Xl, copy=False, nan=0.0, posinf=0.0, neginf=0.0)
    yl = y[sub]
    mean = Xl.mean(axis=0)
    scale = Xl.std(axis=0)
    scale[scale < 1e-9] = 1.0
    Xl -= mean
    Xl /= scale
    np.clip(Xl, -8.0, 8.0, out=Xl)
    lr = LogisticRegression(C=LOGI_C, max_iter=1000, solver="lbfgs")
    lr.fit(Xl, yl)
    del Xl
    np.savez(os.path.join(model_directory_path, "logistic.npz"),
             keep=keep, mean=mean.astype(np.float64),
             scale=scale.astype(np.float64),
             coef=lr.coef_[0], intercept=np.array([lr.intercept_[0]]))


def infer(
    datasets: Iterable[Tuple[List[float], Iterable[float]]],
    model_directory_path: str,
):
    """Stream per-step break probabilities in [0, 1] (GBT + logistic blend)."""
    import lightgbm as lgb

    boosters, keeps = [], []
    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        boosters.append(lgb.Booster(
            model_file=os.path.join(model_directory_path, f"lgbm_{mi}.txt")))
        keeps.append(_keep_for(version))
    rows = [np.empty((1, len(k)), dtype=np.float64) for k in keeps]
    w_gbt = (1.0 - W_LIN) / len(boosters)

    lg = np.load(os.path.join(model_directory_path, "logistic.npz"))
    l_keep = lg["keep"]
    l_mean = lg["mean"]
    l_scale = lg["scale"]
    l_coef = lg["coef"]
    l_int = float(lg["intercept"][0])

    det = StreamingDetector()

    yield  # signal readiness

    for x_historical, x_online in datasets:
        det.calibrate(np.asarray(x_historical, dtype=np.float64))
        for point in x_online:
            feats = det.update(float(point))
            acc = 0.0
            for b, keep, row in zip(boosters, keeps, rows):
                row[0] = feats[keep]
                p = float(b.predict(row)[0])
                p = min(max(p, 1e-7), 1.0 - 1e-7)
                acc += math.log(p / (1.0 - p)) * w_gbt
            # logistic logit on the v2 subset
            xv = feats[l_keep]
            xs = (xv - l_mean) / l_scale
            np.clip(xs, -8.0, 8.0, out=xs)
            lin_logit = float(np.dot(xs, l_coef)) + l_int
            acc += W_LIN * lin_logit
            score = 1.0 / (1.0 + math.exp(-acc))
            if score < 0.0:
                score = 0.0
            elif score > 1.0:
                score = 1.0
            yield score
'''

# The ensemble members, set here and substituted into the wrapper. Rounds are
# frozen from each model's TS-AUC-selected best_iteration (meta.json).
ENSEMBLE_RECIPES = [
    (42, 374, "v2"),     # model_003  (best_iter 374)
    (7, 231, "v2"),      # model_008  (best_iter 231)
    (2026, 306, "v2"),   # model_009  (best_iter 306)
    (42, 348, "v4"),     # model_015  (best_iter 348)
]


def main() -> None:
    with open(F2) as fh:
        src2 = fh.read()
    with open(F3) as fh:
        src3 = fh.read()
    with open(F4) as fh:
        src4 = fh.read()

    body2 = _strip_to(src2, "import bisect")
    body2 = _rename(body2, {
        "FEATURE_NAMES": "_FN2", "N_FEATURES": "_NF2",
        "StreamingDetector": "_Det2",
    })

    body3 = _strip_to(src3, "DSTREAM_WINDOWS")
    body3 = _drop_import_block(body3, "features2")
    body3 = _rename(body3, {
        "_V2Detector": "_Det2", "V2_FEATURE_NAMES": "_FN2",
        "FEATURE_NAMES": "_FN3", "N_FEATURES": "_NF3",
        "StreamingDetector": "_Det3",
    })

    body4 = _strip_to(src4, "HM_WINDOWS")
    body4 = _drop_import_block(body4, "features3")
    body4 = _rename(body4, {
        "_V3Detector": "_Det3", "V3_FEATURE_NAMES": "_FN3",
        "StreamingDetector": "_Det4",
    })
    # v4 keeps the public FEATURE_NAMES / N_FEATURES; bind the public detector.
    body4 += "\n\nStreamingDetector = _Det4\n"

    wrapper = WRAPPER.replace("__ENSEMBLE__", repr(ENSEMBLE_RECIPES))

    out = HEADER + body2 + "\n\n" + body3 + "\n\n" + body4 + wrapper
    os.makedirs("submission", exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(out)
    print(f"Wrote {OUT} ({len(out)} chars); ensemble={len(ENSEMBLE_RECIPES)} members")


if __name__ == "__main__":
    main()
