"""Generate submission/main.py = round-13 ROBUST model: a single model class
(LightGBM) on the FULL feature bank (v4 + xs + wave = 213 unique feats), 3 seeds,
strongly regularized. NO neural / logistic / rank members.

Rationale (experiments.md R13): the 12-round blend overfits — its VAL is 0.619 but
real ~0.594, and an honest 5-fold *series-disjoint* CV of a single regularized GBT
on this bank is 0.597 ± 0.011 (≈ the real score, and the new xs/wave blocks lift it
+0.0022 as FOUNDATIONS even though they wash out as blend add-ons). The public LB is
one draw; the FINAL ranking is on a private draw, where the simple robust model is
the safer bet. This submission tests "simple-robust ≥ overfit-complex" on the board.

Inlines src/sb/features{2,3,4}.py (the v4 detector), features_xs.py, features_wave.py
into one combined streaming detector. Deterministic, pure numpy + lightgbm (no torch).

Run:  uv run python scripts/make_submission6.py
"""
from __future__ import annotations

import os
import re

F2, F3, F4 = "src/sb/features2.py", "src/sb/features3.py", "src/sb/features4.py"
FXS, FWAVE = "src/sb/features_xs.py", "src/sb/features_wave.py"
OUT = "submission/main.py"

HEADER = '''"""ADIA Lab Structural Break Real-Time — ROBUST submission (round 13).

AUTO-GENERATED by scripts/make_submission6.py — do not edit by hand; edit the
feature sources and regenerate.

Strategy: O(1) streaming tracker with PER-SERIES EMPIRICAL-NULL CALIBRATION over a
LARGE feature bank (v4 calibrated + xs PIT/dependence + wave multi-resolution =
213 features), fed to a SINGLE model class: a 3-seed, strongly-regularized
LightGBM ensemble. No neural/logistic/rank members — a deliberately simple, robust
model that generalizes (honest series-disjoint CV 0.597), the safer private-LB bet.
"""
from __future__ import annotations

import bisect
import math
import os
from collections import deque
from typing import Iterable, List, Optional, Tuple

import numpy as np
'''

WRAPPER = '''

# ----------------------------------------------------------------------------
# Combined streaming extractor: v4 (calibrated) + xs (PIT/dependence) + wave (MRA)
# ----------------------------------------------------------------------------
FEATURE_NAMES = list(_FN4) + list(_FNXS) + list(_FNWAVE)
N_FEATURES = len(FEATURE_NAMES)

# pure-time / EXP-008-rejected feats dropped; log_t/t_over_nhist KEPT (round-10).
_DEFAULT_DROP = {
    "t", "log_n_hist", "chi2_cum", "online_acf2", "acf2_diff",
    "w25_chi2", "w50_chi2", "w100_chi2", "w200_chi2", "w400_chi2",
}


def _compute_keep():
    seen = set()
    idx = []
    for i, n in enumerate(FEATURE_NAMES):
        if n in _DEFAULT_DROP or n in seen:
            continue
        seen.add(n)
        idx.append(i)
    return np.asarray(idx, dtype=np.int64), [FEATURE_NAMES[i] for i in idx]


_KEEP, _KEEP_NAMES = _compute_keep()


class StreamingDetector:
    """Runs the three sub-extractors in lockstep; returns the 213-feat bank row."""

    def __init__(self):
        self._d4 = _Det4()
        self._dxs = _DetXS()
        self._dw = _DetWAVE()

    def calibrate(self, x_hist):
        self._d4.calibrate(x_hist)
        self._dxs.calibrate(x_hist)
        self._dw.calibrate(x_hist)
        self.mu_h = self._d4.mu_h
        self.sd_h = self._d4.sd_h

    def update(self, x):
        return np.concatenate((self._d4.update(x), self._dxs.update(x),
                               self._dw.update(x)))


# ----------------------------------------------------------------------------
# Competition interface
# ----------------------------------------------------------------------------
LGB_PARAMS = dict(
    objective="binary", metric="None", boosting_type="gbdt",
    num_leaves=31, learning_rate=0.03, feature_fraction=0.6,
    bagging_fraction=0.8, bagging_freq=1, min_data_in_leaf=2000,
    lambda_l1=1.0, lambda_l2=1.0, max_depth=-1, num_threads=0,
    deterministic=True, force_row_wise=True, verbosity=-1,
)
ENSEMBLE = [(42, 250), (7, 250), (2026, 250)]
RAMP = 50.0


def _build_xyw(datasets):
    det = StreamingDetector()
    X_chunks, y_chunks, w_chunks = [], [], []
    for _id, x_hist, x_online, tau in datasets:
        det.calibrate(np.asarray(x_hist, dtype=np.float64))
        T = len(x_online)
        if T == 0:
            continue
        feats = np.empty((T, len(_KEEP)), dtype=np.float32)
        for i, x in enumerate(x_online):
            feats[i] = det.update(float(x))[_KEEP]
        y = np.zeros(T, dtype=np.int8)
        w = np.ones(T, dtype=np.float64)
        if tau is not None and tau >= 0:
            tau = int(tau)
            y[tau:] = 1
            idx = np.arange(T)
            w[tau:] = np.clip((idx[tau:] - tau) / RAMP, 0.2, 1.0)
        X_chunks.append(feats)
        y_chunks.append(y)
        w_chunks.append(w)
    return (np.vstack(X_chunks), np.concatenate(y_chunks),
            np.concatenate(w_chunks))


def train(
    datasets: List[Tuple[int, List[float], List[float], Optional[int]]],
    model_directory_path: str,
):
    """Fit a deterministic 3-seed regularized LightGBM ensemble on the bank."""
    import lightgbm as lgb

    X, y, w = _build_xyw(datasets)
    dtrain = lgb.Dataset(X, label=y, weight=w, feature_name=_KEEP_NAMES)
    for mi, (seed, rounds) in enumerate(ENSEMBLE):
        params = dict(LGB_PARAMS, seed=seed)
        booster = lgb.train(params, dtrain, num_boost_round=rounds)
        booster.save_model(os.path.join(model_directory_path, f"lgbm_{mi}.txt"))


def infer(
    datasets: Iterable[Tuple[List[float], Iterable[float]]],
    model_directory_path: str,
):
    """Stream per-step break probabilities in [0, 1] (3-seed GBT mean logit)."""
    import lightgbm as lgb

    boosters = [lgb.Booster(model_file=os.path.join(model_directory_path,
                                                     f"lgbm_{mi}.txt"))
                for mi, _ in enumerate(ENSEMBLE)]
    n = len(boosters)
    row = np.empty((1, len(_KEEP)), dtype=np.float64)
    det = StreamingDetector()

    yield  # signal readiness

    for x_historical, x_online in datasets:
        det.calibrate(np.asarray(x_historical, dtype=np.float64))
        for point in x_online:
            row[0] = det.update(float(point))[_KEEP]
            acc = 0.0
            for b in boosters:
                p = float(b.predict(row)[0])
                p = min(max(p, 1e-7), 1.0 - 1e-7)
                acc += math.log(p / (1.0 - p))
            acc /= n
            score = 1.0 / (1.0 + math.exp(-acc))
            if score < 0.0:
                score = 0.0
            elif score > 1.0:
                score = 1.0
            yield score
'''


def _strip_to(src: str, marker: str) -> str:
    return src[src.index(marker):]


def _rename(body: str, mapping: dict) -> str:
    for a, b in mapping.items():
        body = re.sub(rf"\b{re.escape(a)}\b", b, body)
    return body


def _drop_import_block(body: str, module: str) -> str:
    pat = re.compile(rf"from sb\.{module} import \([^)]*\)\n", re.S)
    return pat.sub("", body)


def main() -> None:
    src2 = open(F2).read()
    src3 = open(F3).read()
    src4 = open(F4).read()
    srcxs = open(FXS).read()
    srcw = open(FWAVE).read()

    body2 = _strip_to(src2, "import bisect")
    body2 = _rename(body2, {"FEATURE_NAMES": "_FN2", "N_FEATURES": "_NF2",
                            "StreamingDetector": "_Det2"})

    body3 = _strip_to(src3, "DSTREAM_WINDOWS")
    body3 = _drop_import_block(body3, "features2")
    body3 = _rename(body3, {"_V2Detector": "_Det2", "V2_FEATURE_NAMES": "_FN2",
                            "FEATURE_NAMES": "_FN3", "N_FEATURES": "_NF3",
                            "StreamingDetector": "_Det3"})

    body4 = _strip_to(src4, "HM_WINDOWS")
    body4 = _drop_import_block(body4, "features3")
    body4 = _rename(body4, {"_V3Detector": "_Det3", "V3_FEATURE_NAMES": "_FN3",
                            "FEATURE_NAMES": "_FN4", "N_FEATURES": "_NF4",
                            "StreamingDetector": "_Det4"})

    bodyxs = _strip_to(srcxs, "XS_WINDOWS")
    bodyxs = _rename(bodyxs, {"FEATURE_NAMES": "_FNXS", "N_FEATURES": "_NFXS",
                              "StreamingDetector": "_DetXS", "_names": "_xs_names"})

    bodyw = _strip_to(srcw, "N_LEVELS = 6")
    bodyw = _rename(bodyw, {"FEATURE_NAMES": "_FNWAVE", "N_FEATURES": "_NFWAVE",
                            "StreamingDetector": "_DetWAVE", "_names": "_wave_names"})

    out = (HEADER + "\n\n" + body2 + "\n\n" + body3 + "\n\n" + body4 + "\n\n"
           + bodyxs + "\n\n" + bodyw + WRAPPER)
    os.makedirs("submission", exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(out)
    print(f"Wrote {OUT} ({len(out)} chars)")


if __name__ == "__main__":
    main()
