"""Generate the self-contained submission/main.py from src/sb/features.py.

Inlines the canonical feature extractor (the cloud can't import our package) and
appends the competition train()/infer() interface. Run after changing features.

Run:  uv run python scripts/make_submission.py
"""
from __future__ import annotations

import os

FEATURES = "src/sb/features.py"
OUT = "submission/main.py"

HEADER = '''"""ADIA Lab Structural Break Real-Time — self-contained submission.

AUTO-GENERATED by scripts/make_submission.py from src/sb/features.py — do not
edit by hand; edit the source and regenerate so train/serve stay in parity.

Strategy (O(1) streaming meta-feature tracker + LightGBM):
  * train(): stream every training series through the O(1) StreamingDetector,
    build (feature, per-step-label) pairs, fit a deterministic LightGBM binary
    classifier. Near-undetectable fresh-break rows are down-weighted; raw `t`
    and `log_n_hist` are dropped (kept: log_t & t_over_nhist for time-normalised
    interactions). Iteration count is frozen from local TS-AUC model selection.
  * infer(): per series, calibrate the historical baseline, then stream each
    online point through ~O(1) state updates and yield a break probability.

Deterministic (no RNG in the feature path; LightGBM deterministic=True) and well
within the 15h budget (~10 min for the full 10k-series test set).
"""
from __future__ import annotations

import os
from typing import Iterable, List, Optional, Tuple

import joblib
'''

WRAPPER = '''

# ----------------------------------------------------------------------------
# Competition interface
# ----------------------------------------------------------------------------
DROP_FEATURES = {
    "t", "log_n_hist",
    "chi2_cum", "online_acf2", "acf2_diff",
    "w25_chi2", "w50_chi2", "w100_chi2", "w200_chi2",
}
KEEP_IDX = [i for i, n in enumerate(FEATURE_NAMES) if n not in DROP_FEATURES]
KEEP_NAMES = [FEATURE_NAMES[i] for i in KEEP_IDX]

LGB_PARAMS = dict(
    objective="binary", metric="None", boosting_type="gbdt",
    num_leaves=31, learning_rate=0.03, feature_fraction=0.8,
    bagging_fraction=0.8, bagging_freq=1, min_data_in_leaf=1000,
    num_threads=0, seed=42, deterministic=True, force_row_wise=True,
    verbosity=-1,
)
NUM_ROUNDS = 288   # frozen from local TS-AUC selection (held-out VAL TS-AUC 0.5812)
RAMP = 50.0        # down-weight near-undetectable fresh-break positives


def train(
    datasets: List[Tuple[int, List[float], List[float], Optional[int]]],
    model_directory_path: str,
):
    """Fit a deterministic LightGBM break detector on streaming meta-features."""
    import lightgbm as lgb

    det = StreamingDetector()
    X_chunks, y_chunks, w_chunks = [], [], []
    keep = KEEP_IDX
    for _id, x_hist, x_online, tau in datasets:
        det.calibrate(np.asarray(x_hist, dtype=np.float64))
        T = len(x_online)
        if T == 0:
            continue
        feats = np.empty((T, N_FEATURES), dtype=np.float32)
        for i, x in enumerate(x_online):
            feats[i] = det.update(float(x))
        y = np.zeros(T, dtype=np.int8)
        w = np.ones(T, dtype=np.float64)
        if tau is not None and tau >= 0:
            tau = int(tau)
            y[tau:] = 1
            idx = np.arange(T)
            w[tau:] = np.clip((idx[tau:] - tau) / RAMP, 0.2, 1.0)
        X_chunks.append(feats[:, keep])
        y_chunks.append(y)
        w_chunks.append(w)

    X = np.vstack(X_chunks)
    y = np.concatenate(y_chunks)
    w = np.concatenate(w_chunks)
    dtrain = lgb.Dataset(X, label=y, weight=w, feature_name=list(KEEP_NAMES))
    booster = lgb.train(LGB_PARAMS, dtrain, num_boost_round=NUM_ROUNDS)
    booster.save_model(os.path.join(model_directory_path, "lgbm.txt"))


def infer(
    datasets: Iterable[Tuple[List[float], Iterable[float]]],
    model_directory_path: str,
):
    """Stream per-step break probabilities in [0, 1]."""
    import lightgbm as lgb

    booster = lgb.Booster(model_file=os.path.join(model_directory_path, "lgbm.txt"))
    keep = KEEP_IDX
    det = StreamingDetector()
    row = np.empty((1, len(keep)), dtype=np.float64)

    yield  # signal readiness

    for x_historical, x_online in datasets:
        det.calibrate(np.asarray(x_historical, dtype=np.float64))
        for point in x_online:
            feats = det.update(float(point))
            row[0] = feats[keep]
            score = float(booster.predict(row)[0])
            if score < 0.0:
                score = 0.0
            elif score > 1.0:
                score = 1.0
            yield score
'''


def main() -> None:
    with open(FEATURES) as fh:
        src = fh.read()
    # drop module docstring + the future import; keep from the first real import.
    marker = "import bisect"
    body = src[src.index(marker):]
    os.makedirs("submission", exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(HEADER + body + WRAPPER)
    print(f"Wrote {OUT} ({len(HEADER+body+WRAPPER)} chars)")


if __name__ == "__main__":
    main()
