"""Generate submission/main.py = the round-5 model: the round-3 GBT+logistic
ensemble PLUS a deterministic pure-numpy neural sub-ensemble that now mixes
*two* recurrent model classes -- GRU and LSTM -- averaged into one member.

Why round 5: the 4 GBTs correlate 0.97-0.99 (ensembling saturated); the GRU
sub-ensemble (round 4) added the first real model-class diversity (rank-corr
~0.83) and lifted VAL 0.6041 -> 0.6161. The remaining lever is *more decorrelated
neural members*. GRU and LSTM gate differently (LSTM has a separate cell state),
so an LSTM is a genuinely different recurrence; averaging GRU+LSTM step-logits
denoises the neural member further than more GRU seeds would.

The cloud has no torch, so every neural member is trained locally
(scripts/train_seq.py --arch {gru,lstm}), its weights exported to numpy, and
EMBEDDED here as base64. infer() runs the exact single-layer recurrence in
float64 numpy -> fully deterministic and O(H) per step. train() still rebuilds
the GBTs + logistic deterministically.

Blend (logit space):
    base   = (1 - W_LIN) * mean(GBT logits) + W_LIN * logistic_logit
    final  = (1 - W_GRU) * base + W_GRU * mean(neural member logits)

Run:  SB_SEQ_DIRS="dir1,dir2,..." SB_W_GRU=0.40 uv run python scripts/make_submission5.py
"""
from __future__ import annotations

import base64
import os
import re

import numpy as np

F2, F3, F4 = "src/sb/features2.py", "src/sb/features3.py", "src/sb/features4.py"
OUT = "submission/main.py"

# Neural members to embed (each a directory containing gru.npz, which may hold a
# GRU or LSTM as flagged by its "kind" field). Order doesn't matter; their step-
# logits are averaged. Override via SB_SEQ_DIRS (comma-separated); SB_GRU_DIRS is
# accepted as a back-compat alias.
SEQ_DIRS = os.environ.get(
    "SB_SEQ_DIRS",
    os.environ.get(
        "SB_GRU_DIRS",
        "artifacts/models/model_020_gru_nolog,artifacts/models/model_021_gru_nolog,"
        "artifacts/models/model_022_gru_nolog",
    ),
).split(",")

# Optional causal-attention member(s). Empty by default (opt-in): when set, each
# dir must hold an attn.npz (serve-format, scale A already baked into the head by
# serve_attn.py valgate). Multiple dirs (seeds) are averaged into ONE neural member.
ATTN_DIRS = [d for d in os.environ.get("SB_ATTN_DIRS", "").split(",") if d.strip()]

# Round-10 retune: the real leaderboard proved VAL (2000 series) tracks the public
# score and the 100-series reduced test is noise. A full VAL blend search (full +
# both honest halves) + an honest cross-half meta-stacker found the logistic was
# OVERWEIGHTED (it even earns a negative stack weight; corr 0.93 with the GBTs) and
# the rank member slightly overweighted. W_LIN 0.2->0.1, RANK_GW 0.15->0.10 lifts
# VAL 0.6166->0.6170 with both halves up. (GRU weight W_GRU=0.45 stayed optimal.)
W_LIN = float(os.environ.get("SB_W_LIN", "0.1"))   # logistic weight within base
W_GRU = float(os.environ.get("SB_W_GRU", "0.45"))  # neural-member weight vs base

# Round-8 metric-aligned member: a LightGBM rank_xendcg booster grouped by online
# step. Frozen + embedded like the neural members; mixed into the GBT base mean as
# a 5th member (rescaled to GBT-logit scale). The rank member is the diversity gold
# of the blend (corr ~0.42 with the GBTs, the lowest of any member). Trained log_t-
# free (model_034_xendcg, 151 feats); the recurrent members are likewise nolog
# (nolog GRU 0.6072 VAL > withlog GRU 0.6048) -- but the GBTs/logistic KEEP log_t
# (round-10 finding below). RANK_GW 0.10 is the VAL-tuned weight.
RANK_DIR = os.environ.get("SB_RANK_DIR", "artifacts/models/model_034_xendcg")
RANK_GW = float(os.environ.get("SB_RANK_GW", "0.10"))  # rank weight inside GBT mean


HEADER = '''"""ADIA Lab Structural Break Real-Time — self-contained submission (round 5).

AUTO-GENERATED by scripts/make_submission5.py from src/sb/features{2,3,4}.py and
the locally-trained recurrent weights — do not edit by hand; edit the sources and
regenerate so train/serve stay in parity.

Strategy: O(1) streaming tracker with PER-SERIES EMPIRICAL-NULL CALIBRATION
feeding a deterministic ensemble of (a) LightGBM seed/feature-set members,
(b) a logistic member (model-class diversity), and (c) a recurrent neural
sub-ensemble (GRU + LSTM) whose recurrence integrates break evidence over time
(a different inductive bias from trees -> real decorrelation, the round-4/5 lift).

The recurrent nets are trained offline (PyTorch); their weights are embedded
below as base64 and run here through exact single-layer GRU/LSTM recurrences in
float64 numpy, so inference is fully deterministic (no torch, no RNG) and O(H)
per step.
"""
from __future__ import annotations

import base64
import io
import os
from typing import Iterable, List, Optional, Tuple

import joblib
import bisect
import math
from collections import deque

import numpy as np
'''


SEQNET_CODE = '''

# ----------------------------------------------------------------------------
# Deterministic pure-numpy recurrent members (match torch.nn.GRU/LSTM exactly)
# ----------------------------------------------------------------------------
def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


class StreamingGRU:
    """O(H)-per-step single-layer GRU + linear head -> per-step logit."""

    CLIP = 8.0
    __slots__ = ("Wih", "Whh", "bih", "bhh", "Wo", "bo", "mean", "scale", "keep",
                 "H", "_H2", "h", "is_raw")

    def __init__(self, p, name_to_col, is_raw=False):
        self.Wih = np.ascontiguousarray(p["Wih"], dtype=np.float64)
        self.Whh = np.ascontiguousarray(p["Whh"], dtype=np.float64)
        # keep input/hidden biases separate: the n-gate gates b_hn by r.
        self.bih = np.asarray(p["bih"], dtype=np.float64)
        self.bhh = np.asarray(p["bhh"], dtype=np.float64)
        self.Wo = np.asarray(p["Wo"], dtype=np.float64)
        self.bo = float(p["bo"])
        self.mean = np.asarray(p["mean"], dtype=np.float64)
        self.scale = np.asarray(p["scale"], dtype=np.float64)
        self.keep = np.asarray([name_to_col[n] for n in
                                [str(s) for s in p["feature_names"]]],
                               dtype=np.int64)
        self.H = int(self.Whh.shape[1])
        self._H2 = 2 * self.H
        self.h = np.zeros(self.H, dtype=np.float64)
        self.is_raw = bool(is_raw)

    def reset(self):
        self.h = np.zeros(self.H, dtype=np.float64)

    def step(self, feats):
        H, H2 = self.H, self._H2
        xs = (feats[self.keep] - self.mean) / self.scale
        np.clip(xs, -self.CLIP, self.CLIP, out=xs)
        np.nan_to_num(xs, copy=False)
        h = self.h
        gi = self.Wih @ xs + self.bih
        gh = self.Whh @ h + self.bhh
        r = _sigmoid(gi[:H] + gh[:H])
        z = _sigmoid(gi[H:H2] + gh[H:H2])
        n = np.tanh(gi[H2:] + r * gh[H2:])
        h = (1.0 - z) * n + z * h
        self.h = h
        return float(self.Wo @ h + self.bo)


class StreamingLSTM:
    """O(H)-per-step single-layer LSTM + linear head -> per-step logit."""

    CLIP = 8.0
    __slots__ = ("Wih", "Whh", "bih", "Wo", "bo", "mean", "scale", "keep",
                 "H", "_H2", "_H3", "h", "c", "is_raw")

    def __init__(self, p, name_to_col, is_raw=False):
        self.Wih = np.ascontiguousarray(p["Wih"], dtype=np.float64)
        self.Whh = np.ascontiguousarray(p["Whh"], dtype=np.float64)
        self.bih = (np.asarray(p["bih"], dtype=np.float64)
                    + np.asarray(p["bhh"], dtype=np.float64))
        self.Wo = np.asarray(p["Wo"], dtype=np.float64)
        self.bo = float(p["bo"])
        self.mean = np.asarray(p["mean"], dtype=np.float64)
        self.scale = np.asarray(p["scale"], dtype=np.float64)
        self.keep = np.asarray([name_to_col[n] for n in
                                [str(s) for s in p["feature_names"]]],
                               dtype=np.int64)
        self.H = int(self.Whh.shape[1])
        self._H2 = 2 * self.H
        self._H3 = 3 * self.H
        self.h = np.zeros(self.H, dtype=np.float64)
        self.c = np.zeros(self.H, dtype=np.float64)
        self.is_raw = bool(is_raw)

    def reset(self):
        self.h = np.zeros(self.H, dtype=np.float64)
        self.c = np.zeros(self.H, dtype=np.float64)

    def step(self, feats):
        H, H2, H3 = self.H, self._H2, self._H3
        xs = (feats[self.keep] - self.mean) / self.scale
        np.clip(xs, -self.CLIP, self.CLIP, out=xs)
        np.nan_to_num(xs, copy=False)
        g = self.Wih @ xs + self.Whh @ self.h + self.bih
        i = _sigmoid(g[:H])
        f = _sigmoid(g[H:H2])
        gg = np.tanh(g[H2:H3])
        o = _sigmoid(g[H3:])
        c = f * self.c + i * gg
        h = o * np.tanh(c)
        self.c = c
        self.h = h
        return float(self.Wo @ h + self.bo)


# --- causal-attention member: O(t)-per-step float64, growing per-layer K/V cache
# (causal => past K/V frozen => cacheable). Reproduces the train_attn EVAL forward
# EXACTLY (norm_first, MHA scale 1/sqrt(head_dim), exact erf-GELU, LayerNorm eps
# 1e-5 biased var). Calib order = nan_to_num FIRST then (x-mean)/scale then clip
# (matches the EVALUATED model, NOT the GRU normalize-first order).
try:
    from scipy.special import erf as _erf
except Exception:  # pragma: no cover
    def _erf(x):
        x = np.asarray(x, dtype=np.float64)
        s = np.sign(x); ax = np.abs(x)
        tt = 1.0 / (1.0 + 0.3275911 * ax)
        poly = tt * (0.254829592 + tt * (-0.284496736 + tt * (
            1.421413741 + tt * (-1.453152027 + tt * 1.061405429))))
        return s * (1.0 - poly * np.exp(-ax * ax))

_SQRT2 = np.sqrt(2.0)


def _gelu(x):
    return 0.5 * x * (1.0 + _erf(x / _SQRT2))


def _layernorm(x, w, b, eps=1e-5):
    mu = x.mean()
    var = ((x - mu) ** 2).mean()
    return (x - mu) / np.sqrt(var + eps) * w + b


class _AttnCache:
    __slots__ = ("buf", "n")

    def __init__(self, d):
        self.buf = np.zeros((64, d), dtype=np.float64)
        self.n = 0

    def append(self, v):
        if self.n == self.buf.shape[0]:
            self.buf = np.concatenate([self.buf, np.zeros_like(self.buf)], axis=0)
        self.buf[self.n] = v
        self.n += 1

    @property
    def arr(self):
        return self.buf[: self.n]


class StreamingAttn:
    """O(t)-per-step causal Transformer member -> per-step logit (float64)."""

    CLIP = 8.0
    is_raw = False

    def __init__(self, p, name_to_col):
        F, d, heads, layers, ff = (int(v) for v in p["__config"])
        self.d, self.heads, self.layers = d, heads, layers
        self.hd = d // heads
        self.attn_scale = 1.0 / np.sqrt(self.hd)
        self.Wproj = np.ascontiguousarray(p["proj.weight"], dtype=np.float64)
        self.bproj = np.asarray(p["proj.bias"], dtype=np.float64)
        self.Whead = np.asarray(p["head.weight"], dtype=np.float64)[0]
        self.bhead = float(np.asarray(p["head.bias"])[0])
        self.layer = []
        for l in range(layers):
            pre = "enc.layers.%d." % l
            self.layer.append({
                "inW": np.ascontiguousarray(p[pre + "self_attn.in_proj_weight"], np.float64),
                "inB": np.asarray(p[pre + "self_attn.in_proj_bias"], np.float64),
                "outW": np.ascontiguousarray(p[pre + "self_attn.out_proj.weight"], np.float64),
                "outB": np.asarray(p[pre + "self_attn.out_proj.bias"], np.float64),
                "l1W": np.ascontiguousarray(p[pre + "linear1.weight"], np.float64),
                "l1B": np.asarray(p[pre + "linear1.bias"], np.float64),
                "l2W": np.ascontiguousarray(p[pre + "linear2.weight"], np.float64),
                "l2B": np.asarray(p[pre + "linear2.bias"], np.float64),
                "n1W": np.asarray(p[pre + "norm1.weight"], np.float64),
                "n1B": np.asarray(p[pre + "norm1.bias"], np.float64),
                "n2W": np.asarray(p[pre + "norm2.weight"], np.float64),
                "n2B": np.asarray(p[pre + "norm2.bias"], np.float64),
            })
        self.mean = np.asarray(p["__mean"], dtype=np.float64)
        self.scale = np.asarray(p["__scale"], dtype=np.float64)
        self.keep = np.asarray([name_to_col[n] for n in
                                [str(s) for s in p["__feature_names"]]],
                               dtype=np.int64)
        self.reset()

    def reset(self):
        self.Kc = [_AttnCache(self.d) for _ in range(self.layers)]
        self.Vc = [_AttnCache(self.d) for _ in range(self.layers)]

    def step(self, feats):
        d, hd = self.d, self.hd
        xs = feats[self.keep].astype(np.float64)
        np.nan_to_num(xs, copy=False)
        xs = (xs - self.mean) / self.scale
        np.clip(xs, -self.CLIP, self.CLIP, out=xs)
        h = self.Wproj @ xs + self.bproj
        for l in range(self.layers):
            P = self.layer[l]
            a = _layernorm(h, P["n1W"], P["n1B"])
            qkv = P["inW"] @ a + P["inB"]
            q = qkv[:d]; k = qkv[d:2 * d]; v = qkv[2 * d:]
            self.Kc[l].append(k); self.Vc[l].append(v)
            K = self.Kc[l].arr; V = self.Vc[l].arr
            ctx = np.empty(d, dtype=np.float64)
            for hh in range(self.heads):
                sl = slice(hh * hd, (hh + 1) * hd)
                sc = (K[:, sl] @ q[sl]) * self.attn_scale
                sc -= sc.max()
                w = np.exp(sc); w /= w.sum()
                ctx[sl] = w @ V[:, sl]
            h = h + (P["outW"] @ ctx + P["outB"])
            f = _layernorm(h, P["n2W"], P["n2B"])
            h = h + (P["l2W"] @ _gelu(P["l1W"] @ f + P["l1B"]) + P["l2B"])
        return float(self.Whead @ h + self.bhead)


# Embedded recurrent weights (base64-encoded .npz), decoded at load time.
_SEQ_B64 = __SEQ_B64__
_ATTN_B64 = __ATTN_B64__

# Raw-stream members consume per-step transforms of the historically-standardized
# raw value z=(x-mu_h)/sd_h instead of the 152 calibrated features (a different
# INPUT -> maximal decorrelation). Order/clip must match scripts/build_raw_stream.
_RAW_CLIP = 8.0
_RAW_NAME_TO_COL = {"z": 0, "z2": 1, "absz": 2}


def _raw_vec(point, mu_h, sd_h):
    z = (point - mu_h) / sd_h
    if z > _RAW_CLIP:
        z = _RAW_CLIP
    elif z < -_RAW_CLIP:
        z = -_RAW_CLIP
    return np.array([z, z * z, abs(z)], dtype=np.float64)


def _load_seqnets(name_to_col):
    nets = []
    for blob in _SEQ_B64:
        d = np.load(io.BytesIO(base64.b64decode(blob)), allow_pickle=True)
        p = {k: d[k] for k in d.files}
        kind = str(p["kind"]) if "kind" in p else "gru"
        is_raw = bool(p["raw"]) if "raw" in p else False
        n2c = _RAW_NAME_TO_COL if is_raw else name_to_col
        cls = StreamingLSTM if kind == "lstm" else StreamingGRU
        nets.append(cls(p, n2c, is_raw))
    return nets


def _load_attns(name_to_col):
    nets = []
    for blob in _ATTN_B64:
        d = np.load(io.BytesIO(base64.b64decode(blob)), allow_pickle=True)
        p = {k: d[k] for k in d.files}
        nets.append(StreamingAttn(p, name_to_col))
    return nets


# back-compat alias (round-4 eval scripts import _load_grus)
_load_grus = _load_seqnets
'''


WRAPPER = '''

# ----------------------------------------------------------------------------
# Competition interface
# ----------------------------------------------------------------------------
# Round-10 correction: log_t is KEPT for the GBTs/logistic. Submission #6 dropped
# it on the strength of the 100-series reduced-OOS test (+0.0203 there) and the
# real public score REGRESSED 0.5987 -> 0.5959. VAL (2000 series) had said log_t
# HELPS (-0.012 if dropped) and the leaderboard agreed -> VAL is the trustworthy
# gate; the 100-series reduced test is noise. log_t restored here.
_DEFAULT_DROP = {
    "t", "log_n_hist", "chi2_cum", "online_acf2", "acf2_diff",
    "w25_chi2", "w50_chi2", "w100_chi2", "w200_chi2", "w400_chi2",
}
_NAME_SET = set(FEATURE_NAMES)
_NAME_TO_COL = {n: i for i, n in enumerate(FEATURE_NAMES)}

_RANK_B64 = __RANK_B64__
RANK_GW = __RANK_GW__


def _load_rank():
    """Decode the embedded rank_xendcg booster + its feature->column map."""
    import lightgbm as lgb
    b = lgb.Booster(model_str=base64.b64decode(_RANK_B64).decode("ascii"))
    keep = np.asarray([_NAME_TO_COL[n] for n in b.feature_name()], dtype=np.int64)
    return b, keep


def _keep_for(version):
    if version == "v2":
        allowed = set(_FN2)
    elif version == "v3":
        allowed = set(_FN3)
    else:
        allowed = set(FEATURE_NAMES)
    return [i for i, n in enumerate(FEATURE_NAMES)
            if n in allowed and n not in _DEFAULT_DROP]


LGB_PARAMS = dict(
    objective="binary", metric="None", boosting_type="gbdt",
    num_leaves=31, learning_rate=0.03, feature_fraction=0.8,
    bagging_fraction=0.8, bagging_freq=1, min_data_in_leaf=1000,
    num_threads=0, seed=42, deterministic=True, force_row_wise=True,
    verbosity=-1,
)
ENSEMBLE = __ENSEMBLE__
RAMP = 50.0
W_LIN = __W_LIN__   # logistic weight inside the base ensemble
W_GRU = __W_GRU__   # neural-member weight vs the base ensemble
LOGI_C = 0.5


def _build_xyw(datasets):
    det = StreamingDetector()
    X_chunks, y_chunks, w_chunks = [], [], []
    for _id, x_hist, x_online, tau in datasets:
        det.calibrate(np.asarray(x_hist, dtype=np.float64))
        T = len(x_online)
        if T == 0:
            continue
        feats = np.empty((T, N_FEATURES), dtype=np.float32)
        for i, x in enumerate(x_online):
            feats[i] = det.update(float(x))
        y = np.zeros(T, dtype=np.int8)
        w = np.ones(T, dtype=np.float64)
        if tau is not None and tau >= 0:
            tau = int(tau)
            y[tau:] = 1
            idx = np.arange(T)
            w[tau:] = np.clip((idx[tau:] - tau) / RAMP, 0.2, 1.0)
        X_chunks.append(feats)
        y_chunks.append(y)
        w_chunks.append(w)
    return (np.vstack(X_chunks), np.concatenate(y_chunks),
            np.concatenate(w_chunks))


def train(
    datasets: List[Tuple[int, List[float], List[float], Optional[int]]],
    model_directory_path: str,
):
    """Fit the deterministic LightGBM ensemble + logistic on streaming feats.

    The neural member(s) are pre-trained (embedded as base64) and need no fitting
    here; the cloud lacks torch. Training code is scripts/train_seq.py for the
    Out-of-Sample retraining phase.
    """
    import lightgbm as lgb

    X, y, w = _build_xyw(datasets)

    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        keep = _keep_for(version)
        names = [FEATURE_NAMES[i] for i in keep]
        dtrain = lgb.Dataset(X[:, keep], label=y, weight=w, feature_name=names)
        params = dict(LGB_PARAMS, seed=seed)
        booster = lgb.train(params, dtrain, num_boost_round=rounds)
        booster.save_model(os.path.join(model_directory_path, f"lgbm_{mi}.txt"))
        del dtrain

    from sklearn.linear_model import LogisticRegression
    keep = np.asarray(_keep_for("v2"), dtype=np.int64)
    sub = slice(None, None, 5)
    Xl = X[sub][:, keep].astype(np.float32)
    np.nan_to_num(Xl, copy=False, nan=0.0, posinf=0.0, neginf=0.0)
    yl = y[sub]
    mean = Xl.mean(axis=0)
    scale = Xl.std(axis=0)
    scale[scale < 1e-9] = 1.0
    Xl -= mean
    Xl /= scale
    np.clip(Xl, -8.0, 8.0, out=Xl)
    lr = LogisticRegression(C=LOGI_C, max_iter=1000, solver="lbfgs")
    lr.fit(Xl, yl)
    del Xl
    np.savez(os.path.join(model_directory_path, "logistic.npz"),
             keep=keep, mean=mean.astype(np.float64),
             scale=scale.astype(np.float64),
             coef=lr.coef_[0], intercept=np.array([lr.intercept_[0]]))

    # ---- rank member: frozen booster (embedded); compute the rescale constants
    # that map its score onto THIS run's GBT-logit scale (consistent at serve).
    rb, rkeep = _load_rank()
    s5 = slice(None, None, 5)
    Xr = X[s5]
    rsc = rb.predict(Xr[:, rkeep])
    gl = np.zeros(Xr.shape[0], dtype=np.float64)
    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        bb = lgb.Booster(
            model_file=os.path.join(model_directory_path, f"lgbm_{mi}.txt"))
        pb = np.clip(bb.predict(Xr[:, _keep_for(version)]), 1e-7, 1.0 - 1e-7)
        gl += np.log(pb / (1.0 - pb))
    gl /= len(ENSEMBLE)
    np.savez(os.path.join(model_directory_path, "rank_const.npz"),
             rk_mu=float(rsc.mean()), rk_sd=float(rsc.std() + 1e-12),
             gbt_mu=float(gl.mean()), gbt_sd=float(gl.std() + 1e-12))


def infer(
    datasets: Iterable[Tuple[List[float], Iterable[float]]],
    model_directory_path: str,
):
    """Stream per-step break probabilities in [0, 1] (GBT + logistic + neural)."""
    import lightgbm as lgb

    boosters, keeps = [], []
    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        boosters.append(lgb.Booster(
            model_file=os.path.join(model_directory_path, f"lgbm_{mi}.txt")))
        keeps.append(_keep_for(version))
    rows = [np.empty((1, len(k)), dtype=np.float64) for k in keeps]
    w_gbt = (1.0 - W_LIN) / len(boosters)

    lg = np.load(os.path.join(model_directory_path, "logistic.npz"))
    l_keep = lg["keep"]
    l_mean = lg["mean"]
    l_scale = lg["scale"]
    l_coef = lg["coef"]
    l_int = float(lg["intercept"][0])

    seqs = _load_seqnets(_NAME_TO_COL)
    attns = _load_attns(_NAME_TO_COL)
    calib_seqs = [g for g in seqs if not g.is_raw]
    raw_seqs = [g for g in seqs if g.is_raw]
    n_members = len(seqs) + (1 if attns else 0)
    w_seq = (1.0 / n_members) if n_members else 0.0

    rank_b, rank_keep = _load_rank()
    rc = np.load(os.path.join(model_directory_path, "rank_const.npz"))
    rk_mu = float(rc["rk_mu"]); rk_sd = float(rc["rk_sd"])
    gbt_mu = float(rc["gbt_mu"]); gbt_sd = float(rc["gbt_sd"])
    rank_row = np.empty((1, len(rank_keep)), dtype=np.float64)

    det = StreamingDetector()

    yield  # signal readiness

    for x_historical, x_online in datasets:
        det.calibrate(np.asarray(x_historical, dtype=np.float64))
        for g in seqs:
            g.reset()
        for a in attns:
            a.reset()
        mu_h = det.mu_h
        sd_h = det.sd_h
        for point in x_online:
            feats = det.update(float(point))
            acc = 0.0
            for b, keep, row in zip(boosters, keeps, rows):
                row[0] = feats[keep]
                p = float(b.predict(row)[0])
                p = min(max(p, 1e-7), 1.0 - 1e-7)
                acc += math.log(p / (1.0 - p)) * w_gbt
            xv = feats[l_keep]
            xs = (xv - l_mean) / l_scale
            np.clip(xs, -8.0, 8.0, out=xs)
            lin_logit = float(np.dot(xs, l_coef)) + l_int
            mean4 = acc / (1.0 - W_LIN)
            rank_row[0] = feats[rank_keep]
            rraw = float(rank_b.predict(rank_row)[0])
            rank_as_gbt = (rraw - rk_mu) / rk_sd * gbt_sd + gbt_mu
            gbt5 = (1.0 - RANK_GW) * mean4 + RANK_GW * rank_as_gbt
            base_logit = (1.0 - W_LIN) * gbt5 + W_LIN * lin_logit
            if seqs or attns:
                seq_logit = 0.0
                for g in calib_seqs:
                    seq_logit += g.step(feats)
                if raw_seqs:
                    rv = _raw_vec(float(point), mu_h, sd_h)
                    for g in raw_seqs:
                        seq_logit += g.step(rv)
                if attns:
                    asum = 0.0
                    for a in attns:
                        asum += a.step(feats)
                    seq_logit += asum / len(attns)
                seq_logit *= w_seq
                final_logit = (1.0 - W_GRU) * base_logit + W_GRU * seq_logit
            else:
                final_logit = base_logit
            score = 1.0 / (1.0 + math.exp(-final_logit))
            if score < 0.0:
                score = 0.0
            elif score > 1.0:
                score = 1.0
            yield score
'''


ENSEMBLE_RECIPES = [
    (42, 374, "v2"),
    (7, 231, "v2"),
    (2026, 306, "v2"),
    (42, 348, "v4"),
]


def _strip_to(src: str, marker: str) -> str:
    return src[src.index(marker):]


def _rename(body: str, mapping: dict) -> str:
    for a, b in mapping.items():
        body = re.sub(rf"\b{re.escape(a)}\b", b, body)
    return body


def _drop_import_block(body: str, module: str) -> str:
    pat = re.compile(rf"from sb\.{module} import \([^)]*\)\n", re.S)
    return pat.sub("", body)


def _embed_seqs() -> list:
    blobs = []
    for d in SEQ_DIRS:
        d = d.strip()
        path = os.path.join(d, "gru.npz")
        if not os.path.exists(path):
            raise FileNotFoundError(f"missing neural weights: {path}")
        with open(path, "rb") as fh:
            blobs.append(base64.b64encode(fh.read()).decode("ascii"))
        kind = "gru"
        try:
            kd = np.load(path, allow_pickle=True)
            if "kind" in kd.files:
                kind = str(kd["kind"])
        except Exception:
            pass
        print(f"  embedded {kind.upper()} {path} "
              f"({os.path.getsize(path)/1024:.0f} KB)")
    return blobs


def _embed_attns() -> list:
    blobs = []
    for d in ATTN_DIRS:
        d = d.strip()
        path = os.path.join(d, "attn.npz")
        if not os.path.exists(path):
            raise FileNotFoundError(f"missing attention weights: {path}")
        with open(path, "rb") as fh:
            blobs.append(base64.b64encode(fh.read()).decode("ascii"))
        print(f"  embedded ATTN {path} "
              f"({os.path.getsize(path)/1024:.0f} KB)")
    return blobs


def main() -> None:
    with open(F2) as fh:
        src2 = fh.read()
    with open(F3) as fh:
        src3 = fh.read()
    with open(F4) as fh:
        src4 = fh.read()

    body2 = _strip_to(src2, "import bisect")
    body2 = _rename(body2, {
        "FEATURE_NAMES": "_FN2", "N_FEATURES": "_NF2",
        "StreamingDetector": "_Det2",
    })

    body3 = _strip_to(src3, "DSTREAM_WINDOWS")
    body3 = _drop_import_block(body3, "features2")
    body3 = _rename(body3, {
        "_V2Detector": "_Det2", "V2_FEATURE_NAMES": "_FN2",
        "FEATURE_NAMES": "_FN3", "N_FEATURES": "_NF3",
        "StreamingDetector": "_Det3",
    })

    body4 = _strip_to(src4, "HM_WINDOWS")
    body4 = _drop_import_block(body4, "features3")
    body4 = _rename(body4, {
        "_V3Detector": "_Det3", "V3_FEATURE_NAMES": "_FN3",
        "StreamingDetector": "_Det4",
    })
    body4 += "\n\nStreamingDetector = _Det4\n"

    blobs = _embed_seqs()
    attn_blobs = _embed_attns()
    seqnet = (SEQNET_CODE
              .replace("__SEQ_B64__", repr(blobs))
              .replace("__ATTN_B64__", repr(attn_blobs)))
    with open(os.path.join(RANK_DIR, "lgbm_rank.txt"), "rb") as fh:
        rank_blob = base64.b64encode(fh.read()).decode("ascii")
    print(f"  embedded RANK {RANK_DIR}/lgbm_rank.txt "
          f"({os.path.getsize(os.path.join(RANK_DIR, 'lgbm_rank.txt'))/1024:.0f} KB)"
          f"  gw={RANK_GW}")
    wrapper = (WRAPPER
               .replace("__ENSEMBLE__", repr(ENSEMBLE_RECIPES))
               .replace("__W_LIN__", repr(W_LIN))
               .replace("__W_GRU__", repr(W_GRU))
               .replace("__RANK_B64__", repr(rank_blob))
               .replace("__RANK_GW__", repr(RANK_GW)))

    out = HEADER + body2 + "\n\n" + body3 + "\n\n" + body4 + seqnet + wrapper
    os.makedirs("submission", exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(out)
    print(f"Wrote {OUT} ({len(out)} chars); {len(ENSEMBLE_RECIPES)} GBT + "
          f"{len(blobs)} neural + {len(attn_blobs)} attn members; "
          f"W_LIN={W_LIN} W_GRU={W_GRU}")


if __name__ == "__main__":
    main()
