"""Generate self-contained submission/main.py from features2.py + features3.py.

Inlines both extractor modules (the cloud can't import our package), strips the
cross-module import, and appends the competition train()/infer() interface with
a deterministic multi-seed LightGBM ensemble (mean-logit blend).

Run:  uv run python scripts/make_submission2.py
"""
from __future__ import annotations

import os
import re

F2 = "src/sb/features2.py"
F3 = "src/sb/features3.py"
OUT = "submission/main.py"

HEADER = '''"""ADIA Lab Structural Break Real-Time — self-contained submission.

AUTO-GENERATED by scripts/make_submission2.py from src/sb/features2.py +
src/sb/features3.py — do not edit by hand; edit the sources and regenerate so
train/serve stay in parity.

Strategy (round 3): O(1) streaming tracker + per-series empirical-null
calibration + LightGBM seed ensemble.
  * Every window statistic is normalised by the null loc/scale measured on the
    series' own break-free historical segment at dyadic scales (8..512) —
    TS-AUC is a cross-sectional ranking, so per-series calibration is what
    makes scores comparable across heterogeneous DGPs.
  * Multiscale scan maxima + running-max of the calibrated stats, AR(1)-
    prewhitened CUSUM bank, derived-stream (|z| / dz / median-crossing)
    calibrated windows.
  * train(): build (feature, step-label) rows for all training series, fit
    N_SEEDS deterministic LightGBM binary classifiers (fresh-break positives
    down-weighted by an elapsed ramp). Round counts frozen from local TS-AUC
    selection.
  * infer(): per series, calibrate -> stream O(1) updates -> mean-logit of the
    seed ensemble -> probability in [0, 1].

Deterministic (no RNG in the feature path; LightGBM deterministic=True).
"""
from __future__ import annotations

import os
from typing import Iterable, List, Optional, Tuple

import joblib
'''

WRAPPER = '''

# ----------------------------------------------------------------------------
# Competition interface
# ----------------------------------------------------------------------------
DROP_FEATURES = {
    "t", "log_n_hist",
    "chi2_cum", "online_acf2", "acf2_diff",
    "w25_chi2", "w50_chi2", "w100_chi2", "w200_chi2", "w400_chi2",
}
KEEP_IDX = [i for i, n in enumerate(FEATURE_NAMES) if n not in DROP_FEATURES]
KEEP_NAMES = [FEATURE_NAMES[i] for i in KEEP_IDX]

LGB_PARAMS = dict(
    objective="binary", metric="None", boosting_type="gbdt",
    num_leaves=31, learning_rate=0.03, feature_fraction=0.8,
    bagging_fraction=0.8, bagging_freq=1, min_data_in_leaf=1000,
    num_threads=0, seed=42, deterministic=True, force_row_wise=True,
    verbosity=-1,
)
ENSEMBLE = [   # (seed, num_rounds frozen from local TS-AUC selection)
    (42, 374),
    (7, 374),
    (2026, 374),
]
RAMP = 50.0        # down-weight near-undetectable fresh-break positives


def train(
    datasets: List[Tuple[int, List[float], List[float], Optional[int]]],
    model_directory_path: str,
):
    """Fit the deterministic LightGBM seed ensemble on streaming meta-features."""
    import lightgbm as lgb

    det = StreamingDetector()
    X_chunks, y_chunks, w_chunks = [], [], []
    keep = KEEP_IDX
    for _id, x_hist, x_online, tau in datasets:
        det.calibrate(np.asarray(x_hist, dtype=np.float64))
        T = len(x_online)
        if T == 0:
            continue
        feats = np.empty((T, N_FEATURES), dtype=np.float32)
        for i, x in enumerate(x_online):
            feats[i] = det.update(float(x))
        y = np.zeros(T, dtype=np.int8)
        w = np.ones(T, dtype=np.float64)
        if tau is not None and tau >= 0:
            tau = int(tau)
            y[tau:] = 1
            idx = np.arange(T)
            w[tau:] = np.clip((idx[tau:] - tau) / RAMP, 0.2, 1.0)
        X_chunks.append(feats[:, keep])
        y_chunks.append(y)
        w_chunks.append(w)

    X = np.vstack(X_chunks)
    y = np.concatenate(y_chunks)
    w = np.concatenate(w_chunks)
    del X_chunks, y_chunks, w_chunks
    dtrain = lgb.Dataset(X, label=y, weight=w, feature_name=list(KEEP_NAMES),
                         free_raw_data=True)
    dtrain.construct()
    del X, y, w
    for seed, rounds in ENSEMBLE:
        params = dict(LGB_PARAMS, seed=seed)
        booster = lgb.train(params, dtrain, num_boost_round=rounds)
        booster.save_model(os.path.join(model_directory_path, f"lgbm_s{seed}.txt"))


def infer(
    datasets: Iterable[Tuple[List[float], Iterable[float]]],
    model_directory_path: str,
):
    """Stream per-step break probabilities in [0, 1] (mean-logit ensemble)."""
    import lightgbm as lgb

    boosters = [
        lgb.Booster(model_file=os.path.join(model_directory_path, f"lgbm_s{seed}.txt"))
        for seed, _ in ENSEMBLE
    ]
    keep = KEEP_IDX
    det = StreamingDetector()
    row = np.empty((1, len(keep)), dtype=np.float64)
    inv_k = 1.0 / len(boosters)

    yield  # signal readiness

    for x_historical, x_online in datasets:
        det.calibrate(np.asarray(x_historical, dtype=np.float64))
        for point in x_online:
            feats = det.update(float(point))
            row[0] = feats[keep]
            acc = 0.0
            for b in boosters:
                p = float(b.predict(row)[0])
                p = min(max(p, 1e-7), 1.0 - 1e-7)
                acc += math.log(p / (1.0 - p))
            score = 1.0 / (1.0 + math.exp(-acc * inv_k))
            if score < 0.0:
                score = 0.0
            elif score > 1.0:
                score = 1.0
            yield score
'''


def main() -> None:
    with open(F2) as fh:
        src2 = fh.read()
    with open(F3) as fh:
        src3 = fh.read()

    # features2: drop module docstring/future import; keep from first import.
    body2 = src2[src2.index("import bisect"):]
    # When inlined into ONE module, v2 and v3 would share the mutable globals
    # FEATURE_NAMES / N_FEATURES. The v2 detector's _features() reads N_FEATURES
    # to size its output array, so it must stay pinned at the v2 count (127).
    # Rename the v2 module globals to v2-specific names so v2 stays consistent
    # while v3 owns the public FEATURE_NAMES / N_FEATURES.
    body2 = re.sub(r"\bFEATURE_NAMES\b", "FEATURE_NAMES_V2", body2)
    body2 = re.sub(r"\bN_FEATURES\b", "N_FEATURES_V2", body2)

    # features3: keep from after the v2 import block (it shares the namespace
    # once inlined); also drop its own stdlib imports (already present).
    m = re.search(r"^DSTREAM_WINDOWS", src3, flags=re.M)
    body3 = src3[m.start():]
    # the v3 detector subclasses the inlined v2 detector under its own name
    body3 = body3.replace("class StreamingDetector(_V2Detector):",
                          "class StreamingDetectorV3(StreamingDetector):")
    body3 = body3.replace("V2_FEATURE_NAMES", "FEATURE_NAMES_V2")
    # drop the original module-level name definitions (they reference the
    # sb.features2 import); re-derive them explicitly after the class instead.
    body3 = re.sub(
        r"FEATURE_NAMES = FEATURE_NAMES_V2 \+ _DS_NAMES \+ _DS_SCAN \+ _DS_CONST\n"
        r"N_FEATURES = len\(FEATURE_NAMES\)\n"
        r"_N_V2 = len\(FEATURE_NAMES_V2\)\n",
        "", body3, count=1)
    body3 += (
        "\n\n_N_V2 = len(FEATURE_NAMES_V2)\n"
        "FEATURE_NAMES = FEATURE_NAMES_V2 + _DS_NAMES + _DS_SCAN + _DS_CONST\n"
        "N_FEATURES = len(FEATURE_NAMES)\n"
        "StreamingDetector = StreamingDetectorV3\n"
    )
    if "_N_V2 = len(FEATURE_NAMES_V2)\nFEATURE_NAMES" not in body3:
        raise SystemExit("features3 module-level rebind not assembled cleanly")


    os.makedirs("submission", exist_ok=True)
    out = HEADER + body2 + "\n\n" + body3 + WRAPPER
    with open(OUT, "w") as fh:
        fh.write(out)
    print(f"Wrote {OUT} ({len(out)} chars)")


if __name__ == "__main__":
    main()
