"""Generate submission/main.py = the round-4 model: the round-3 GBT+logistic
ensemble PLUS deterministic pure-numpy GRU sequence member(s).

Why: the 4 GBTs correlate 0.97-0.99 (ensembling saturated) and the logistic
member (corr 0.93) already showed model-class diversity is the remaining lever.
A recurrent net integrates evidence over time -- a genuinely different inductive
bias (rank-corr ~0.90 vs the base), so it decorrelates and lifts the blend.

The cloud has no torch, so the GRU is trained locally (scripts/train_seq.py),
its weights exported to numpy, and EMBEDDED here as base64. infer() runs the
exact single-layer GRU recurrence in float64 numpy -> fully deterministic and
O(H) per step. train() still rebuilds the GBTs + logistic deterministically.

Blend (logit space):
    base   = (1 - W_LIN) * mean(GBT logits) + W_LIN * logistic_logit
    final  = (1 - W_GRU) * base + W_GRU * mean(GRU logits)

Run:  uv run python scripts/make_submission4.py
"""
from __future__ import annotations

import base64
import glob
import os
import re

import numpy as np

F2, F3, F4 = "src/sb/features2.py", "src/sb/features3.py", "src/sb/features4.py"
OUT = "submission/main.py"

# GRU members to embed (each a directory with gru.npz). Order doesn't matter;
# their logits are averaged. Override via SB_GRU_DIRS (comma-separated).
GRU_DIRS = os.environ.get(
    "SB_GRU_DIRS",
    "artifacts/models/model_020_gru",
).split(",")

W_LIN = float(os.environ.get("SB_W_LIN", "0.2"))   # logistic weight within base
W_GRU = float(os.environ.get("SB_W_GRU", "0.25"))  # GRU weight vs base


HEADER = '''"""ADIA Lab Structural Break Real-Time — self-contained submission (round 4).

AUTO-GENERATED by scripts/make_submission4.py from src/sb/features{2,3,4}.py and
the locally-trained GRU weights — do not edit by hand; edit the sources and
regenerate so train/serve stay in parity.

Strategy: O(1) streaming tracker with PER-SERIES EMPIRICAL-NULL CALIBRATION
feeding a deterministic ensemble of (a) LightGBM seed/feature-set members,
(b) a logistic member (model-class diversity), and (c) GRU sequence member(s)
whose recurrence integrates break evidence over time (a different inductive
bias from trees -> real decorrelation, the round-4 lift).

The GRU is trained offline (PyTorch); its weights are embedded below as base64
and run here through an exact single-layer GRU recurrence in float64 numpy, so
inference is fully deterministic (no torch, no RNG) and O(H) per step.
"""
from __future__ import annotations

import base64
import io
import os
from typing import Iterable, List, Optional, Tuple

import joblib
import bisect
import math
from collections import deque

import numpy as np
'''


SEQNET_CODE = '''

# ----------------------------------------------------------------------------
# Deterministic pure-numpy GRU sequence member (matches torch.nn.GRU exactly)
# ----------------------------------------------------------------------------
def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


class StreamingGRU:
    """O(H)-per-step single-layer GRU + linear head -> per-step logit."""

    CLIP = 8.0
    __slots__ = ("Wih", "Whh", "bih", "Wo", "bo", "mean", "scale", "keep",
                 "H", "_H2", "h")

    def __init__(self, p, name_to_col):
        self.Wih = np.ascontiguousarray(p["Wih"], dtype=np.float64)
        self.Whh = np.ascontiguousarray(p["Whh"], dtype=np.float64)
        self.bih = (np.asarray(p["bih"], dtype=np.float64)
                    + np.asarray(p["bhh"], dtype=np.float64))
        self.Wo = np.asarray(p["Wo"], dtype=np.float64)
        self.bo = float(p["bo"])
        self.mean = np.asarray(p["mean"], dtype=np.float64)
        self.scale = np.asarray(p["scale"], dtype=np.float64)
        self.keep = np.asarray([name_to_col[n] for n in
                                [str(s) for s in p["feature_names"]]],
                               dtype=np.int64)
        self.H = int(self.Whh.shape[1])
        self._H2 = 2 * self.H
        self.h = np.zeros(self.H, dtype=np.float64)

    def reset(self):
        self.h = np.zeros(self.H, dtype=np.float64)

    def step(self, feats):
        H, H2 = self.H, self._H2
        xs = (feats[self.keep] - self.mean) / self.scale
        np.clip(xs, -self.CLIP, self.CLIP, out=xs)
        np.nan_to_num(xs, copy=False)
        h = self.h
        g = self.Wih @ xs + self.bih
        gh = self.Whh @ h
        r = _sigmoid(g[:H] + gh[:H])
        z = _sigmoid(g[H:H2] + gh[H:H2])
        n = np.tanh(g[H2:] + r * gh[H2:])
        h = (1.0 - z) * n + z * h
        self.h = h
        return float(self.Wo @ h + self.bo)


# Embedded GRU weights (base64-encoded .npz), decoded at load time.
_GRU_B64 = __GRU_B64__


def _load_grus(name_to_col):
    grus = []
    for blob in _GRU_B64:
        d = np.load(io.BytesIO(base64.b64decode(blob)), allow_pickle=True)
        grus.append(StreamingGRU({k: d[k] for k in d.files}, name_to_col))
    return grus
'''


WRAPPER = '''

# ----------------------------------------------------------------------------
# Competition interface
# ----------------------------------------------------------------------------
_DEFAULT_DROP = {
    "t", "log_n_hist", "chi2_cum", "online_acf2", "acf2_diff",
    "w25_chi2", "w50_chi2", "w100_chi2", "w200_chi2", "w400_chi2",
}
_NAME_SET = set(FEATURE_NAMES)
_NAME_TO_COL = {n: i for i, n in enumerate(FEATURE_NAMES)}


def _keep_for(version):
    if version == "v2":
        allowed = set(_FN2)
    elif version == "v3":
        allowed = set(_FN3)
    else:
        allowed = set(FEATURE_NAMES)
    return [i for i, n in enumerate(FEATURE_NAMES)
            if n in allowed and n not in _DEFAULT_DROP]


LGB_PARAMS = dict(
    objective="binary", metric="None", boosting_type="gbdt",
    num_leaves=31, learning_rate=0.03, feature_fraction=0.8,
    bagging_fraction=0.8, bagging_freq=1, min_data_in_leaf=1000,
    num_threads=0, seed=42, deterministic=True, force_row_wise=True,
    verbosity=-1,
)
ENSEMBLE = __ENSEMBLE__
RAMP = 50.0
W_LIN = __W_LIN__   # logistic weight inside the base ensemble
W_GRU = __W_GRU__   # GRU weight vs the base ensemble
LOGI_C = 0.5


def _build_xyw(datasets):
    det = StreamingDetector()
    X_chunks, y_chunks, w_chunks = [], [], []
    for _id, x_hist, x_online, tau in datasets:
        det.calibrate(np.asarray(x_hist, dtype=np.float64))
        T = len(x_online)
        if T == 0:
            continue
        feats = np.empty((T, N_FEATURES), dtype=np.float32)
        for i, x in enumerate(x_online):
            feats[i] = det.update(float(x))
        y = np.zeros(T, dtype=np.int8)
        w = np.ones(T, dtype=np.float64)
        if tau is not None and tau >= 0:
            tau = int(tau)
            y[tau:] = 1
            idx = np.arange(T)
            w[tau:] = np.clip((idx[tau:] - tau) / RAMP, 0.2, 1.0)
        X_chunks.append(feats)
        y_chunks.append(y)
        w_chunks.append(w)
    return (np.vstack(X_chunks), np.concatenate(y_chunks),
            np.concatenate(w_chunks))


def train(
    datasets: List[Tuple[int, List[float], List[float], Optional[int]]],
    model_directory_path: str,
):
    """Fit the deterministic LightGBM ensemble + logistic on streaming feats.

    The GRU member(s) are pre-trained (embedded as base64) and need no fitting
    here; the cloud lacks torch. Training code is scripts/train_seq.py for the
    Out-of-Sample retraining phase.
    """
    import lightgbm as lgb

    X, y, w = _build_xyw(datasets)

    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        keep = _keep_for(version)
        names = [FEATURE_NAMES[i] for i in keep]
        dtrain = lgb.Dataset(X[:, keep], label=y, weight=w, feature_name=names)
        params = dict(LGB_PARAMS, seed=seed)
        booster = lgb.train(params, dtrain, num_boost_round=rounds)
        booster.save_model(os.path.join(model_directory_path, f"lgbm_{mi}.txt"))
        del dtrain

    from sklearn.linear_model import LogisticRegression
    keep = np.asarray(_keep_for("v2"), dtype=np.int64)
    sub = slice(None, None, 5)
    Xl = X[sub][:, keep].astype(np.float32)
    np.nan_to_num(Xl, copy=False, nan=0.0, posinf=0.0, neginf=0.0)
    yl = y[sub]
    mean = Xl.mean(axis=0)
    scale = Xl.std(axis=0)
    scale[scale < 1e-9] = 1.0
    Xl -= mean
    Xl /= scale
    np.clip(Xl, -8.0, 8.0, out=Xl)
    lr = LogisticRegression(C=LOGI_C, max_iter=1000, solver="lbfgs")
    lr.fit(Xl, yl)
    del Xl
    np.savez(os.path.join(model_directory_path, "logistic.npz"),
             keep=keep, mean=mean.astype(np.float64),
             scale=scale.astype(np.float64),
             coef=lr.coef_[0], intercept=np.array([lr.intercept_[0]]))


def infer(
    datasets: Iterable[Tuple[List[float], Iterable[float]]],
    model_directory_path: str,
):
    """Stream per-step break probabilities in [0, 1] (GBT + logistic + GRU)."""
    import lightgbm as lgb

    boosters, keeps = [], []
    for mi, (seed, rounds, version) in enumerate(ENSEMBLE):
        boosters.append(lgb.Booster(
            model_file=os.path.join(model_directory_path, f"lgbm_{mi}.txt")))
        keeps.append(_keep_for(version))
    rows = [np.empty((1, len(k)), dtype=np.float64) for k in keeps]
    w_gbt = (1.0 - W_LIN) / len(boosters)

    lg = np.load(os.path.join(model_directory_path, "logistic.npz"))
    l_keep = lg["keep"]
    l_mean = lg["mean"]
    l_scale = lg["scale"]
    l_coef = lg["coef"]
    l_int = float(lg["intercept"][0])

    grus = _load_grus(_NAME_TO_COL)
    w_seq = (1.0 / len(grus)) if grus else 0.0

    det = StreamingDetector()

    yield  # signal readiness

    for x_historical, x_online in datasets:
        det.calibrate(np.asarray(x_historical, dtype=np.float64))
        for g in grus:
            g.reset()
        for point in x_online:
            feats = det.update(float(point))
            acc = 0.0
            for b, keep, row in zip(boosters, keeps, rows):
                row[0] = feats[keep]
                p = float(b.predict(row)[0])
                p = min(max(p, 1e-7), 1.0 - 1e-7)
                acc += math.log(p / (1.0 - p)) * w_gbt
            xv = feats[l_keep]
            xs = (xv - l_mean) / l_scale
            np.clip(xs, -8.0, 8.0, out=xs)
            lin_logit = float(np.dot(xs, l_coef)) + l_int
            base_logit = acc + W_LIN * lin_logit
            if grus:
                seq_logit = 0.0
                for g in grus:
                    seq_logit += g.step(feats)
                seq_logit *= w_seq
                final_logit = (1.0 - W_GRU) * base_logit + W_GRU * seq_logit
            else:
                final_logit = base_logit
            score = 1.0 / (1.0 + math.exp(-final_logit))
            if score < 0.0:
                score = 0.0
            elif score > 1.0:
                score = 1.0
            yield score
'''


ENSEMBLE_RECIPES = [
    (42, 374, "v2"),
    (7, 231, "v2"),
    (2026, 306, "v2"),
    (42, 348, "v4"),
]


def _strip_to(src: str, marker: str) -> str:
    return src[src.index(marker):]


def _rename(body: str, mapping: dict) -> str:
    for a, b in mapping.items():
        body = re.sub(rf"\b{re.escape(a)}\b", b, body)
    return body


def _drop_import_block(body: str, module: str) -> str:
    pat = re.compile(rf"from sb\.{module} import \([^)]*\)\n", re.S)
    return pat.sub("", body)


def _embed_grus() -> list:
    blobs = []
    for d in GRU_DIRS:
        d = d.strip()
        path = os.path.join(d, "gru.npz")
        if not os.path.exists(path):
            raise FileNotFoundError(f"missing GRU weights: {path}")
        with open(path, "rb") as fh:
            blobs.append(base64.b64encode(fh.read()).decode("ascii"))
        print(f"  embedded GRU {path} ({os.path.getsize(path)/1024:.0f} KB)")
    return blobs


def main() -> None:
    with open(F2) as fh:
        src2 = fh.read()
    with open(F3) as fh:
        src3 = fh.read()
    with open(F4) as fh:
        src4 = fh.read()

    body2 = _strip_to(src2, "import bisect")
    body2 = _rename(body2, {
        "FEATURE_NAMES": "_FN2", "N_FEATURES": "_NF2",
        "StreamingDetector": "_Det2",
    })

    body3 = _strip_to(src3, "DSTREAM_WINDOWS")
    body3 = _drop_import_block(body3, "features2")
    body3 = _rename(body3, {
        "_V2Detector": "_Det2", "V2_FEATURE_NAMES": "_FN2",
        "FEATURE_NAMES": "_FN3", "N_FEATURES": "_NF3",
        "StreamingDetector": "_Det3",
    })

    body4 = _strip_to(src4, "HM_WINDOWS")
    body4 = _drop_import_block(body4, "features3")
    body4 = _rename(body4, {
        "_V3Detector": "_Det3", "V3_FEATURE_NAMES": "_FN3",
        "StreamingDetector": "_Det4",
    })
    body4 += "\n\nStreamingDetector = _Det4\n"

    blobs = _embed_grus()
    seqnet = SEQNET_CODE.replace("__GRU_B64__", repr(blobs))
    wrapper = (WRAPPER
               .replace("__ENSEMBLE__", repr(ENSEMBLE_RECIPES))
               .replace("__W_LIN__", repr(W_LIN))
               .replace("__W_GRU__", repr(W_GRU)))

    out = HEADER + body2 + "\n\n" + body3 + "\n\n" + body4 + seqnet + wrapper
    os.makedirs("submission", exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(out)
    print(f"Wrote {OUT} ({len(out)} chars); {len(ENSEMBLE_RECIPES)} GBT + "
          f"{len(blobs)} GRU members; W_LIN={W_LIN} W_GRU={W_GRU}")


if __name__ == "__main__":
    main()
